--  -*- encoding: utf-8 -*-
--
--  Ada specification generated by ZBMCompile.
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Formatting;

package ZanyBlue.Text.CLDR_Data is

   --  Since the body calls the Initialize procedure, this package need
   --  only be with'ed.  Suppress any compiler warnings about an unused
   --  with'ed package.
   pragma Warnings (Off, ZanyBlue.Text.CLDR_Data);

   package ZT  renames ZanyBlue.Text;
   package ZTC renames ZanyBlue.Text.Catalogs;
   package ZTF renames ZanyBlue.Text.Formatting;

   Facility_1 : aliased constant Wide_String := "l";
   Facility_2 : aliased constant Wide_String := "s";
   Facility_3 : aliased constant Wide_String := "t";
   Facilities : constant ZT.Constant_String_List (1 .. 3) := (
                   Facility_1'Access,
                   Facility_2'Access,
                   Facility_3'Access);

   procedure Initialize (Catalog : ZTC.Catalog_Type := ZTF.Standard_Catalog);

end ZanyBlue.Text.CLDR_Data;
