--
--  Ada specification generated by ZBMCompile.
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Formatting;

package ZanyBlue.Test.Text.Catalogs.Xmpl_Data3 is

   package ZT  renames ZanyBlue.Text;
   package ZTC renames ZanyBlue.Text.Catalogs;
   package ZTF renames ZanyBlue.Text.Formatting;

   Facility_1 : aliased constant Wide_String := "f1";
   Facility_2 : aliased constant Wide_String := "f2";
   Facilities : constant ZT.Constant_String_List := (
                   1 => Facility_1'Access,
                   2 => Facility_2'Access);

   procedure Initialize (Catalog : ZTC.Catalog_Type := ZTF.Standard_Catalog);

end ZanyBlue.Test.Text.Catalogs.Xmpl_Data3;
