--  -*- encoding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V1.0.0 - BETA.
--  This is a generated file and should not be edited.
--

package body ZBMCompile.Messages is

   package ZT  renames ZanyBlue.Text;
   package ZTC renames ZanyBlue.Text.Catalogs;

   subtype Z is ZTC.ZBMCompile_Definition;

   Facility_1 : aliased constant Wide_String := "zbmcompile";
   Facility_2 : aliased constant Wide_String := "zbmbase";
   Facility_3 : aliased constant Wide_String := "zbmprints";
   Facility_4 : aliased constant Wide_String := "zbmwprints";
   Facility_5 : aliased constant Wide_String := "zbmwstrings";
   Facility_6 : aliased constant Wide_String := "zbmstrings";
   Facility_7 : aliased constant Wide_String := "zbmexceptions";
   Facilities : constant ZT.Constant_String_List (1 .. 7) := (
                   1 => Facility_1'Access,
                   2 => Facility_2'Access,
                   3 => Facility_3'Access,
                   4 => Facility_4'Access,
                   5 => Facility_5'Access,
                   6 => Facility_6'Access,
                   7 => Facility_7'Access);

   Key_1 : aliased constant Wide_String := "00004";
   Key_2 : aliased constant Wide_String := "10027";
   Key_3 : aliased constant Wide_String := "20010";
   Key_4 : aliased constant Wide_String := "20008";
   Key_5 : aliased constant Wide_String := "10028";
   Key_6 : aliased constant Wide_String := "10009";
   Key_7 : aliased constant Wide_String := "00009";
   Key_8 : aliased constant Wide_String := "00007";
   Key_9 : aliased constant Wide_String := "10026";
   Key_10 : aliased constant Wide_String := "10025";
   Key_11 : aliased constant Wide_String := "10001";
   Key_12 : aliased constant Wide_String := "20001";
   Key_13 : aliased constant Wide_String := "00001";
   Key_14 : aliased constant Wide_String := "20007";
   Key_15 : aliased constant Wide_String := "00008";
   Key_16 : aliased constant Wide_String := "10003";
   Key_17 : aliased constant Wide_String := "00006";
   Key_18 : aliased constant Wide_String := "10005";
   Key_19 : aliased constant Wide_String := "10002";
   Key_20 : aliased constant Wide_String := "00029";
   Key_21 : aliased constant Wide_String := "10006";
   Key_22 : aliased constant Wide_String := "00050";
   Key_23 : aliased constant Wide_String := "00034";
   Key_24 : aliased constant Wide_String := "10020";
   Key_25 : aliased constant Wide_String := "00035";
   Key_26 : aliased constant Wide_String := "00036";
   Key_27 : aliased constant Wide_String := "00032";
   Key_28 : aliased constant Wide_String := "10019";
   Key_29 : aliased constant Wide_String := "10007";
   Key_30 : aliased constant Wide_String := "00059";
   Key_31 : aliased constant Wide_String := "00058";
   Key_32 : aliased constant Wide_String := "10014";
   Key_33 : aliased constant Wide_String := "00028";
   Key_34 : aliased constant Wide_String := "00027";
   Key_35 : aliased constant Wide_String := "00033";
   Key_36 : aliased constant Wide_String := "20006";
   Key_37 : aliased constant Wide_String := "00014";
   Key_38 : aliased constant Wide_String := "00055";
   Key_39 : aliased constant Wide_String := "00037";
   Key_40 : aliased constant Wide_String := "10018";
   Key_41 : aliased constant Wide_String := "00030";
   Key_42 : aliased constant Wide_String := "00003";
   Key_43 : aliased constant Wide_String := "00002";
   Key_44 : aliased constant Wide_String := "20003";
   Key_45 : aliased constant Wide_String := "00020";
   Key_46 : aliased constant Wide_String := "00056";
   Key_47 : aliased constant Wide_String := "10015";
   Key_48 : aliased constant Wide_String := "10008";
   Key_49 : aliased constant Wide_String := "00042";
   Key_50 : aliased constant Wide_String := "10016";
   Key_51 : aliased constant Wide_String := "00052";
   Key_52 : aliased constant Wide_String := "00057";
   Key_53 : aliased constant Wide_String := "00012";
   Key_54 : aliased constant Wide_String := "00024";
   Key_55 : aliased constant Wide_String := "00038";
   Key_56 : aliased constant Wide_String := "10004";
   Key_57 : aliased constant Wide_String := "00026";
   Key_58 : aliased constant Wide_String := "00054";
   Key_59 : aliased constant Wide_String := "00031";
   Key_60 : aliased constant Wide_String := "10017";
   Key_61 : aliased constant Wide_String := "00039";
   Key_62 : aliased constant Wide_String := "10011";
   Key_63 : aliased constant Wide_String := "00053";
   Key_64 : aliased constant Wide_String := "00016";
   Key_65 : aliased constant Wide_String := "00045";
   Key_66 : aliased constant Wide_String := "00023";
   Key_67 : aliased constant Wide_String := "00048";
   Key_68 : aliased constant Wide_String := "00046";
   Key_69 : aliased constant Wide_String := "00049";
   Key_70 : aliased constant Wide_String := "00017";
   Key_71 : aliased constant Wide_String := "00025";
   Key_72 : aliased constant Wide_String := "00047";
   Key_73 : aliased constant Wide_String := "00040";
   Key_74 : aliased constant Wide_String := "00010";
   Key_75 : aliased constant Wide_String := "00044";
   Key_76 : aliased constant Wide_String := "20009";
   Key_77 : aliased constant Wide_String := "00018";
   Key_78 : aliased constant Wide_String := "00005";
   Key_79 : aliased constant Wide_String := "00011";
   Key_80 : aliased constant Wide_String := "10012";
   Key_81 : aliased constant Wide_String := "00022";
   Key_82 : aliased constant Wide_String := "00021";
   Key_83 : aliased constant Wide_String := "10010";
   Key_84 : aliased constant Wide_String := "00051";
   Key_85 : aliased constant Wide_String := "00043";
   Key_86 : aliased constant Wide_String := "00013";
   Key_87 : aliased constant Wide_String := "00015";
   Key_88 : aliased constant Wide_String := "20005";
   Key_89 : aliased constant Wide_String := "20002";
   Key_90 : aliased constant Wide_String := "10029";
   Key_91 : aliased constant Wide_String := "10013";
   Key_92 : aliased constant Wide_String := "00041";
   Key_93 : aliased constant Wide_String := "10022";
   Key_94 : aliased constant Wide_String := "20004";
   Key_95 : aliased constant Wide_String := "00000";
   Key_96 : aliased constant Wide_String := "10023";
   Key_97 : aliased constant Wide_String := "10024";
   Key_98 : aliased constant Wide_String := "20011";
   Key_99 : aliased constant Wide_String := "10030";
   Key_100 : aliased constant Wide_String := "10021";
   Key_101 : aliased constant Wide_String := "00019";
   Keys : constant ZT.Constant_String_List (1 .. 101) := (
                   1 => Key_1'Access,
                   2 => Key_2'Access,
                   3 => Key_3'Access,
                   4 => Key_4'Access,
                   5 => Key_5'Access,
                   6 => Key_6'Access,
                   7 => Key_7'Access,
                   8 => Key_8'Access,
                   9 => Key_9'Access,
                   10 => Key_10'Access,
                   11 => Key_11'Access,
                   12 => Key_12'Access,
                   13 => Key_13'Access,
                   14 => Key_14'Access,
                   15 => Key_15'Access,
                   16 => Key_16'Access,
                   17 => Key_17'Access,
                   18 => Key_18'Access,
                   19 => Key_19'Access,
                   20 => Key_20'Access,
                   21 => Key_21'Access,
                   22 => Key_22'Access,
                   23 => Key_23'Access,
                   24 => Key_24'Access,
                   25 => Key_25'Access,
                   26 => Key_26'Access,
                   27 => Key_27'Access,
                   28 => Key_28'Access,
                   29 => Key_29'Access,
                   30 => Key_30'Access,
                   31 => Key_31'Access,
                   32 => Key_32'Access,
                   33 => Key_33'Access,
                   34 => Key_34'Access,
                   35 => Key_35'Access,
                   36 => Key_36'Access,
                   37 => Key_37'Access,
                   38 => Key_38'Access,
                   39 => Key_39'Access,
                   40 => Key_40'Access,
                   41 => Key_41'Access,
                   42 => Key_42'Access,
                   43 => Key_43'Access,
                   44 => Key_44'Access,
                   45 => Key_45'Access,
                   46 => Key_46'Access,
                   47 => Key_47'Access,
                   48 => Key_48'Access,
                   49 => Key_49'Access,
                   50 => Key_50'Access,
                   51 => Key_51'Access,
                   52 => Key_52'Access,
                   53 => Key_53'Access,
                   54 => Key_54'Access,
                   55 => Key_55'Access,
                   56 => Key_56'Access,
                   57 => Key_57'Access,
                   58 => Key_58'Access,
                   59 => Key_59'Access,
                   60 => Key_60'Access,
                   61 => Key_61'Access,
                   62 => Key_62'Access,
                   63 => Key_63'Access,
                   64 => Key_64'Access,
                   65 => Key_65'Access,
                   66 => Key_66'Access,
                   67 => Key_67'Access,
                   68 => Key_68'Access,
                   69 => Key_69'Access,
                   70 => Key_70'Access,
                   71 => Key_71'Access,
                   72 => Key_72'Access,
                   73 => Key_73'Access,
                   74 => Key_74'Access,
                   75 => Key_75'Access,
                   76 => Key_76'Access,
                   77 => Key_77'Access,
                   78 => Key_78'Access,
                   79 => Key_79'Access,
                   80 => Key_80'Access,
                   81 => Key_81'Access,
                   82 => Key_82'Access,
                   83 => Key_83'Access,
                   84 => Key_84'Access,
                   85 => Key_85'Access,
                   86 => Key_86'Access,
                   87 => Key_87'Access,
                   88 => Key_88'Access,
                   89 => Key_89'Access,
                   90 => Key_90'Access,
                   91 => Key_91'Access,
                   92 => Key_92'Access,
                   93 => Key_93'Access,
                   94 => Key_94'Access,
                   95 => Key_95'Access,
                   96 => Key_96'Access,
                   97 => Key_97'Access,
                   98 => Key_98'Access,
                   99 => Key_99'Access,
                   100 => Key_100'Access,
                   101 => Key_101'Access);

   Locale_1 : aliased constant Wide_String := "";
   Locales : constant ZT.Constant_String_List (1 .. 1) := (
                   1 => Locale_1'Access);

   Pool_Data_1 : aliased constant Wide_String := ""
      & "Usage: zbmcompile [ options ] package facility"
      & Wide_Character'Val (10)
      & "where available options are"
      & Wide_Character'Val (10)
      & "  -q             Quiet mode"
      & Wide_Character'Val (10)
      & "  -v             Verbose mode"
      & Wide_Character'Val (10)
      & "  -m             Always include argument modes in generated"
      & " code"
      & Wide_Character'Val (10)
      & "  -p             Number list entries (gnatcheck +RPositiona"
      & "l_Components)"
      & Wide_Character'Val (10)
      & "  -D             Debug mode (dump the catalog definitions)"
      & Wide_Character'Val (10)
      & "  -d directory   Directory containing facility (defaults to"
      & " ""."")"
      & Wide_Character'Val (10)
      & "  -e extension   Properties extension (default ""properties"
      & """)"
      & Wide_Character'Val (10)
      & "  -i             Include initialization call in body"
      & Wide_Character'Val (10)
      & "  -O             Optimize string pool for locale based acce"
      & "ss"
      & Wide_Character'Val (10)
      & "  -g             Disable locale based access optimization ("
      & "default)"
      & Wide_Character'Val (10)
      & "  -B             Compile only the base locale"
      & Wide_Character'Val (10)
      & "  -u             Disable consistency checked (unchecked mod"
      & "e)"
      & Wide_Character'Val (10)
      & "  -L locale      Compile only the named locale, e.g., ""fr"""
      & ", ""fr_FR"""
      & Wide_Character'Val (10)
      & "  -r locale      Define reference (base) locale for consist"
      & "ency checking"
      & Wide_Character'Val (10)
      & "  -s locale      Define source root locale"
      & Wide_Character'Val (10)
      & "  -S stamp-file  File to always create/update (contains a t"
      & "imestamp)"
      & Wide_Character'Val (10)
      & "  -x name        Define external name for Initialize proced"
      & "ure"
      & Wide_Character'Val (10)
      & "  -F             Force generation, ignoring errors.  Genera"
      & "ted code might"
      & Wide_Character'Val (10)
      & "                 not compile"
      & Wide_Character'Val (10)
      & "  -C             Disable comments on generated accessor rou"
      & "tines"
      & Wide_Character'Val (10)
      & "  -T item size   Set the size of an Ada output limit: pool "
      & "or comment   ----------------"
      & Wide_Character'Val (10)
      & "   -- Initialize --"
      & Wide_Character'Val (10)
      & "   ----------------"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   procedure Initialize (Catalog :{0}ZTC.Catalog_Type := St"
      & "andard_Catalog) is"
      & Wide_Character'Val (10)
      & "   begin"
      & Wide_Character'Val (10)
      & "      ZTC.Initialize (Catalog, Messages, Pool, Facilities, "
      & "Keys, Locales,"
      & Wide_Character'Val (10)
      & "                      ""{1}"","
      & Wide_Character'Val (10)
      & "                      Pool_Data_1''Length, {2});"
      & Wide_Character'Val (10)
      & "   end Initialize;"
      & Wide_Character'Val (10)
      & "      Write_Message (Destination, Facility ({0}), Key ({1})"
      & ", Arguments,"
      & Wide_Character'Val (10)
      & "                     Format (Facility ({0}), Key ({1}), Arg"
      & "uments,"
      & Wide_Character'Val (10)
      & "                             Locale => Locale, Catalog => C"
      & "atalog),"
      & Wide_Character'Val (10)
      & "                     With_NL, Locale, Catalog);"
      & Wide_Character'Val (10)
      & "   end Print_{2};"
      & Wide_Character'Val (10)
      & "      Destination :{0}File_Type    := Current_Output;"
      & Wide_Character'Val (10)
      & "      With_NL     :{0}Boolean      := True;"
      & Wide_Character'Val (10)
      & "      Locale      :{0}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{0}Catalog_Type := Standard_Catalog)"
      & Wide_Character'Val (10)
      & "   is"
      & Wide_Character'Val (10)
      & "      Arguments : Argument_List;"
      & Wide_Character'Val (10)
      & "   begin   ----------------"
      & Wide_Character'Val (10)
      & "   -- Initialize --"
      & Wide_Character'Val (10)
      & "   ----------------"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   procedure Initialize (Catalog :{0}ZTC.Catalog_Type := St"
      & "andard_Catalog) is"
      & Wide_Character'Val (10)
      & "      pragma Unreferenced (Catalog);"
      & Wide_Character'Val (10)
      & "   begin"
      & Wide_Character'Val (10)
      & "      null;"
      & Wide_Character'Val (10)
      & "   end Initialize;"
      & Wide_Character'Val (10)
      & "      Destination :{1}File_Type    := Current_Output;"
      & Wide_Character'Val (10)
      & "      With_NL     :{1}Boolean      := True;"
      & Wide_Character'Val (10)
      & "      Locale      :{1}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{1}Catalog_Type := Standard_Catalog);   "
      & "--  Since the body calls the Initialize procedure, this pac"
      & "kage need"
      & Wide_Character'Val (10)
      & "   --  only be with''ed.  Suppress any compiler warnings ab"
      & "out an unused"
      & Wide_Character'Val (10)
      & "   --  with''ed package."
      & Wide_Character'Val (10)
      & "   pragma Warnings (Off, {0});"
      & Wide_Character'Val (10)
      & "   procedure Initialize ("
      & Wide_Character'Val (10)
      & "      Catalog :{0}ZanyBlue.Text.Catalogs.Catalog_Type := St"
      & "andard_Catalog);"
      & Wide_Character'Val (10)
      & "   --  The catalog initialization routine: load the compile"
      & "d messages into"
      & Wide_Character'Val (10)
      & "   --  a catalog.   function {0} (Index :{1}Positive) retur"
      & "n Wide_String;"
      & Wide_Character'Val (10)
      & "   --  The name of the Index''th {0} item compiled."
      & Wide_Character'Val (10)
      & "   --  This routine is normally only used by generated acce"
      & "ssor code."
      & Wide_Character'Val (10)
      & "      Locale      :{0}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{0}Catalog_Type := Standard_Catalog) ret"
      & "urn Wide_String"
      & Wide_Character'Val (10)
      & "   is"
      & Wide_Character'Val (10)
      & "      Arguments : Argument_List;"
      & Wide_Character'Val (10)
      & "   begin      Locale      :{0}Locale_Type  := Current_Local"
      & "e;"
      & Wide_Character'Val (10)
      & "      Catalog     :{0}Catalog_Type := Standard_Catalog) ret"
      & "urn String"
      & Wide_Character'Val (10)
      & "   is"
      & Wide_Character'Val (10)
      & "      Arguments : Argument_List;"
      & Wide_Character'Val (10)
      & "   begin   ---{2:-^{3,*}}----------"
      & Wide_Character'Val (10)
      & "   --- {0}_Count --"
      & Wide_Character'Val (10)
      & "   ---{2:-^{3,*}}----------"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   function {0}_Count return Natural is"
      & Wide_Character'Val (10)
      & "   begin"
      & Wide_Character'Val (10)
      & "      return {1}''Length;"
      & Wide_Character'Val (10)
      & "   end {0}_Count;"
      & Wide_Character'Val (10)
      & "   ---{3:-^{4,*}}----"
      & Wide_Character'Val (10)
      & "   --- {0} --"
      & Wide_Character'Val (10)
      & "   ---{3:-^{4,*}}----"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   function {0} (Index :{1}Positive) return Wide_String is"
      & Wide_Character'Val (10)
      & "   begin"
      & Wide_Character'Val (10)
      & "      return {2} (Index).all;"
      & Wide_Character'Val (10)
      & "   end {0};"
      & Wide_Character'Val (10)
      & "--  -*- encoding: utf-8 -*-"
      & Wide_Character'Val (10)
      & "--"
      & Wide_Character'Val (10)
      & "--  Ada implementation generated by ZBMCompile, V{0}.{1}.{2"
      & "} - {3}."
      & Wide_Character'Val (10)
      & "--  This is a generated file and should not be edited."
      & Wide_Character'Val (10)
      & "--"
      & Wide_Character'Val (10)
      & "--  -*- encoding: utf-8 -*-"
      & Wide_Character'Val (10)
      & "--"
      & Wide_Character'Val (10)
      & "--  Ada specification generated by ZBMCompile, V{0}.{1}.{2}"
      & " - {3}."
      & Wide_Character'Val (10)
      & "--  This is a generated file and should not be edited."
      & Wide_Character'Val (10)
      & "--"
      & Wide_Character'Val (10)
      & "   ---------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & "   -- Raise_{0} --"
      & Wide_Character'Val (10)
      & "   ---------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   procedure Raise_{0} ("
      & Wide_Character'Val (10)
      & "      E           :{3}Ada.Exceptions.Exception_Id;   functi"
      & "on {0}_Count return Natural;"
      & Wide_Character'Val (10)
      & "   --  Numnber of {0} items compiled."
      & Wide_Character'Val (10)
      & "   --  This routine is normally only used by generated acce"
      & "ssor code."
      & Wide_Character'Val (10)
      & "      Raise_Exception (E, Facility ({0}), Key ({1}), Argume"
      & "nts,"
      & Wide_Character'Val (10)
      & "                       Locale => Locale, Catalog => Catalog"
      & ");"
      & Wide_Character'Val (10)
      & "   end Raise_{2};"
      & Wide_Character'Val (10)
      & "      Locale      :{1}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{1}Catalog_Type := Standard_Catalog);"
      & Wide_Character'Val (10)
      & "   pragma No_Return (Raise_{0});      return Format (Facili"
      & "ty ({0}), Key ({1}), Arguments,"
      & Wide_Character'Val (10)
      & "                     Locale => Locale, Catalog => Catalog);"
      & Wide_Character'Val (10)
      & "   end Format_{2};"
      & Wide_Character'Val (10)
      & "      Locale      :{1}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{1}Catalog_Type := Standard_Catalog) ret"
      & "urn Wide_String;   package ZT  renames ZanyBlue.Text;"
      & Wide_Character'Val (10)
      & "   package ZTC renames ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   subtype Z is ZTC.ZBMCompile_Definition;"
      & Wide_Character'Val (10)
      & "   function Standard_Catalog return ZanyBlue.Text.Catalogs."
      & "Catalog_Type"
      & Wide_Character'Val (10)
      & "      renames ZanyBlue.Text.Formatting.Standard_Catalog;"
      & Wide_Character'Val (10)
      & "      Locale      :{1}Locale_Type  := Current_Locale;"
      & Wide_Character'Val (10)
      & "      Catalog     :{1}Catalog_Type := Standard_Catalog) ret"
      & "urn String;   use Ada.Wide_Text_IO;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Locales;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Arguments;"
      & Wide_Character'Val (10)
      & "   use Ada.Text_IO;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Locales;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Arguments;"
      & Wide_Character'Val (10)
      & "with Ada.Wide_Text_IO;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Locales;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Arguments;"
      & Wide_Character'Val (10)
      & "with Ada.Exceptions;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Locales;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Arguments;"
      & Wide_Character'Val (10)
      & "with Ada.Text_IO;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Locales;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Arguments;"
      & Wide_Character'Val (10)
      & "   ----------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & "   -- Format_{0} --"
      & Wide_Character'Val (10)
      & "   ----------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   function Format_{0} (   ---------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & "   -- Print_{0} --"
      & Wide_Character'Val (10)
      & "   ---------{1:-^{2,*}}---"
      & Wide_Character'Val (10)
      & Wide_Character'Val (10)
      & "   procedure Print_{0} (""{0}"", line {1}, Error, Illegal f"
      & "ormat for key ""{2}"", character ''{3}'' at position {4}War"
      & "ning, no messages defined for the facility ""{0}"", no acce"
      & "ssor packages createdThis is ZBMCompile, Version {0,*}.{1,*"
      & "}.{2,*} {3} (r{4}) at {5,time} on {5,date}Warning, the key "
      & """{0}"" in the facility ""{1}"" is defined for the locale """
      & "{2}""                    Locale_Index => {0,*}, Source_Loca"
      & "le_Index => {1,*}));Error, too many arguments for key ""{0}"
      & """ in facility ""{1}"" for locale ""{2}""Error, cannot disa"
      & "ble checks (-u) when generating accessors packages (-a)Skip"
      & "ping consistency checks for ""{0}"", base locale (""{1}"") "
      & "is not defined                    Locale_Index => {0,*}, So"
      & "urce_Locale_Index => {1,*}),   procedure Raise_{0}"
      & Wide_Character'Val (10)
      & "     (E           :{1}Ada.Exceptions.Exception_Id;""{0}"", "
      & "line {1}, invalid (non ISO-644) character, use \u escapes i"
      & "nstead""{0}"", line {1}, Error, type mis-match for argument"
      & " {2}: ""{3}"" and ""{4}""   Pool : constant ZT.Static_Messa"
      & "ge_Pool_Type := Pool_Data_1''Access;"
      & Wide_Character'Val (10)
      & """{0}"", line {1}, Error, Format not closed for key ""{2}"""
      & " at position {3}Loaded total {0} characters, stored {1} uni"
      & "que characters, {2}% savingError, no reference definition f"
      & "or the key ""{0}"" in the facility ""{1}""   use ZanyBlue.T"
      & "ext.Arguments;"
      & Wide_Character'Val (10)
      & "   use ZanyBlue.Text.Formatting;"
      & Wide_Character'Val (10)
      & """{0}"", line {1}, duplicate key ""{2}"" previous defined o"
      & "n line {3}Error, invalid accessor type name value, ""{0}"","
      & " for the -G optionPerforming consistency checks for the acc"
      & "essor package generation                    Facility_Index "
      & "=> {0,*}, Key_Index => {1,*},Error, localized messages inco"
      & "nsistent with base locale (""{0}"")ZBMCompile completed at "
      & "{0,time} on {0,date}, elapsed time {1}Copyright (c) 2009-{0"
      & ",*}, Michael Rohan.  All rights reservedwith ZanyBlue.Text."
      & "Arguments;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Formatting;"
      & Wide_Character'Val (10)
      & "Loaded {0} facilities, {1} keys, {2} locales and {3} messag"
      & "esDebug: Writing optimize catalog description to optimized."
      & "dumpwith ZanyBlue.Text.Catalogs;"
      & Wide_Character'Val (10)
      & "with ZanyBlue.Text.Formatting;"
      & Wide_Character'Val (10)
      & "   Messages : constant ZTC.ZBMCompile_List (1 .. {0,*}) := "
      & "(   {0} : constant ZT.Constant_String_List (1 .. {1,*}) := "
      & "(Created the stamp file ""{0}"" containing the time stamp {"
      & "1}                 {0} => Z''(First => {1,*}, Last => {2,*}"
      & ",Error, the name ""{0}"" does not name a valid sizing targe"
      & "tError, the -a and -G options should not be used togetherLo"
      & "aded {0} messages for the facility ""{1}"" ({2} locales)Acc"
      & "umulated messages for the locale ""{0}"" ({1} messages)Erro"
      & "r, the facility ""{0}"" is not a valid Ada identifier   {0}"
      & "_{1,*} : aliased constant Wide_String := ""{2}""{3}{0} erro"
      & "rs detected, forcing generation of Ada sourcesSuppressing b"
      & "ase message comments on accessor routinesPerforming consist"
      & "ency checks for the facility ""{0}""                 Z''(Fi"
      & "rst => {1,*}, Last => {2,*},Error, the key ""{0}"" is not a"
      & " valid Ada identifier                   {1,*} => {0}_{1,*}'"
      & "'Access);Error, the argument ""{0}"" is not a valid numberE"
      & "rror, the option ''{0}'' requires an argument              "
      & "     {1,*} => {0}_{1,*}''Access,Generated accessor package "
      & "spec ""{0}"" to ""{1}""Optimizing the catalog for locale or"
      & "der accessGenerated accessor package body ""{0}"" to ""{1}"""
      & "Retained accessor package spec ""{0}"" in ""{1}""Retained a"
      & "ccessor package body ""{0}"" in ""{1}""Writing messages for"
      & " the locale ""{0}"" ({1})Error, a package name argument is "
      & "required{0} errors detected, no sources generatedRetained t"
      & "he spec ""{0}"" in the file ""{1}""Retained the body ""{0}"""
      & " in the file ""{1}""Error, failed to access the source ""{0"
      & "}""   pragma Export (C, Initialize, ""{0}"");Error, invalid"
      & " command line option ""{0}""      Append (Arguments, Argume"
      & "nt{0,*});Error, no source .properties files givenLoaded {0}"
      & " messages(s) for {1} locale(s)Bootstrap loaded {0} messages"
      & " for ""{1}""                   {0}_{1,*}''Access);Wrote the"
      & " body ""{0}"" to the file ""{1}""Wrote the spec ""{0}"" to "
      & "the file ""{1}""                   {0}_{1,*}''Access,      "
      & "Argument{0,<3*} :{1}{2}''Class;   --  Definition of access "
      & "routines.Invalid command line argument: ""{0}""      & Wide"
      & "_Character''Val ({0,*})Error, failed to create ""{0}"": {1}"
      & """{0}"", line {1}, syntax error: {2}Error, no messages file"
      & "s processedOutput package body file is ""{0}""Output packag"
      & "e spec file is ""{0}""begin  --  {0}"
      & Wide_Character'Val (10)
      & "   Initialize;              others => <>);No files found to"
      & " compileStamp file created on {0}   --  No base messagepack"
      & "age body {0} is"
      & Wide_Character'Val (10)
      & "{0}.{1}_Wide_Strings{0}.{1}_Wide_Prints{0}.{1}_Exceptions{0"
      & "}.{1}_Stringspackage {0} is"
      & Wide_Character'Val (10)
      & "   --  ↦{0}{1}{0}.{1}_Prints      & ""{0}""      & """";"
      & "";
   Pool : constant ZT.Static_Message_Pool_Type := Pool_Data_1'Access;

   Messages : constant ZTC.ZBMCompile_List (1 .. 210) := (
                 1 => Z'(First => 8950, Last => 8996,
                    Facility_Index => 1, Key_Index => 63,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the argument "{0}" is not a valid number
                 2 => Z'(First => 7579, Last => 7642,
                    Facility_Index => 2, Key_Index => 40,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                    Facility_Index => {0,*}, Key_Index ⤶
   --  ↦=> {1,*},
                 3 => Z'(First => 8903, Last => 8949,
                    Facility_Index => 2, Key_Index => 62,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                   {1,*} => {0}_{1,*}''Access);
                 4 => Z'(First => 5825, Last => 5929,
                    Facility_Index => 3, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Text_IO;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
   --  ↦with ZanyBlue.Text.Arguments;⏎
                 5 => Z'(First => 9360, Last => 9401,
                    Facility_Index => 1, Key_Index => 70,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, a package name argument is required
                 6 => Z'(First => 10168, Last => 10201,
                    Facility_Index => 1, Key_Index => 87,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, no messages files processed
                 7 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 5, Key_Index => 94,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package body {0} is⏎
                 8 => Z'(First => 7859, Last => 7889,
                    Facility_Index => 7, Key_Index => 89,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 9 => Z'(First => 6893, Last => 6964,
                    Facility_Index => 1, Key_Index => 30,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, invalid (non ISO-644) character, use \⤶
   --  ↦u escapes instead
                 10 => Z'(First => 5630, Last => 5686,
                    Facility_Index => 5, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
                 11 => Z'(First => 8476, Last => 8531,
                    Facility_Index => 1, Key_Index => 54,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Accumulated messages for the locale "{0}" ({1} messages⤶
   --  ↦)
                 12 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 5, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 13 => Z'(First => 9317, Last => 9359,
                    Facility_Index => 1, Key_Index => 7,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Writing messages for the locale "{0}" ({1})
                 14 => Z'(First => 6297, Last => 6376,
                    Facility_Index => 1, Key_Index => 13,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦This is ZBMCompile, Version {0,*}.{1,*}.{2,*} {3} (r{4}⤶
   --  ↦) at {5,time} on {5,date}
                 15 => Z'(First => 5930, Last => 6030,
                    Facility_Index => 5, Key_Index => 14,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ----------{1:-^{2,*}}---⏎
   --  ↦   -- Format_{0} --⏎
   --  ↦   ----------{1:-^{2,*}}---⏎
   --  ↦⏎
   --  ↦   function Format_{0} (
                 16 => Z'(First => 7384, Last => 7448,
                    Facility_Index => 1, Key_Index => 37,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, duplicate key "{2}" previous defined o⤶
   --  ↦n line {3}
                 17 => Z'(First => 5630, Last => 5716,
                    Facility_Index => 6, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
   --  ↦with ZanyBlue.Text.Arguments;⏎
                 18 => Z'(First => 2967, Last => 3145,
                    Facility_Index => 2, Key_Index => 8,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   function {0} (Index :{1}Positive) return Wide_String⤶
   --  ↦;⏎
   --  ↦   --  The name of the Index''th {0} item compiled.⏎
   --  ↦   --  This routine is normally only used by generated ⤶
   --  ↦accessor code.⏎
                 19 => Z'(First => 4294, Last => 4439,
                    Facility_Index => 2, Key_Index => 15,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   function {0}_Count return Natural;⏎
   --  ↦   --  Numnber of {0} items compiled.⏎
   --  ↦   --  This routine is normally only used by generated ⤶
   --  ↦accessor code.⏎
                 20 => Z'(First => 10504, Last => 10517,
                    Facility_Index => 2, Key_Index => 96,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --  ↦{0}{1}
                 21 => Z'(First => 9992, Last => 10028,
                    Facility_Index => 2, Key_Index => 78,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --  Definition of access routines.
                 22 => Z'(First => 7351, Last => 7383,
                    Facility_Index => 6, Key_Index => 88,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 23 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 7, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 24 => Z'(First => 5717, Last => 5824,
                    Facility_Index => 7, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Exceptions;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
   --  ↦with ZanyBlue.Text.Arguments;⏎
                 25 => Z'(First => 10029, Last => 10064,
                    Facility_Index => 1, Key_Index => 84,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Invalid command line argument: "{0}"
                 26 => Z'(First => 9645, Last => 9684,
                    Facility_Index => 4, Key_Index => 76,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Append (Arguments, Argument{0,*});
                 27 => Z'(First => 9605, Last => 9644,
                    Facility_Index => 1, Key_Index => 75,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, invalid command line option "{0}"
                 28 => Z'(First => 4865, Last => 4993,
                    Facility_Index => 5, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{1}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{1}Catalog_Type := Standard_Catalog)⤶
   --  ↦ return Wide_String;
                 29 => Z'(First => 7890, Last => 7950,
                    Facility_Index => 1, Key_Index => 45,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Loaded {0} facilities, {1} keys, {2} locales and {3} me⤶
   --  ↦ssages
                 30 => Z'(First => 8750, Last => 8801,
                    Facility_Index => 1, Key_Index => 59,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Performing consistency checks for the facility "{0}"
                 31 => Z'(First => 7319, Last => 7383,
                    Facility_Index => 5, Key_Index => 36,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Arguments;⏎
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 32 => Z'(First => 10545, Last => 10555,
                    Facility_Index => 2, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      & "";
                 33 => Z'(First => 8249, Last => 8306,
                    Facility_Index => 2, Key_Index => 50,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                 {0} => Z''(First => {1,*}, Last => {2,⤶
   --  ↦*},
                 34 => Z'(First => 7319, Last => 7383,
                    Facility_Index => 6, Key_Index => 36,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Arguments;⏎
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 35 => Z'(First => 3663, Last => 3831,
                    Facility_Index => 2, Key_Index => 10,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ---{3:-^{4,*}}----⏎
   --  ↦   --- {0} --⏎
   --  ↦   ---{3:-^{4,*}}----⏎
   --  ↦⏎
   --  ↦   function {0} (Index :{1}Positive) return Wide_String⤶
   --  ↦ is⏎
   --  ↦   begin⏎
   --  ↦      return {2} (Index).all;⏎
   --  ↦   end {0};⏎
                 36 => Z'(First => 10474, Last => 10488,
                    Facility_Index => 6, Key_Index => 95,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}.{1}_Strings
                 37 => Z'(First => 6031, Last => 6128,
                    Facility_Index => 3, Key_Index => 14,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦   -- Print_{0} --⏎
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦⏎
   --  ↦   procedure Print_{0} (
                 38 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 4, Key_Index => 94,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package body {0} is⏎
                 39 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 4, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 40 => Z'(First => 6105, Last => 6128,
                    Facility_Index => 4, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   procedure Print_{0} (
                 41 => Z'(First => 9135, Last => 9180,
                    Facility_Index => 1, Key_Index => 66,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Optimizing the catalog for locale order access
                 42 => Z'(First => 7829, Last => 7889,
                    Facility_Index => 4, Key_Index => 44,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Arguments;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 43 => Z'(First => 9645, Last => 9684,
                    Facility_Index => 5, Key_Index => 76,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Append (Arguments, Argument{0,*});
                 44 => Z'(First => 9443, Last => 9483,
                    Facility_Index => 1, Key_Index => 72,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Retained the spec "{0}" in the file "{1}"
                 45 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 5, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 46 => Z'(First => 7351, Last => 7383,
                    Facility_Index => 5, Key_Index => 88,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 47 => Z'(First => 6601, Last => 6673,
                    Facility_Index => 1, Key_Index => 26,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, cannot disable checks (-u) when generating acces⤶
   --  ↦sors packages (-a)
                 48 => Z'(First => 6031, Last => 6128,
                    Facility_Index => 4, Key_Index => 14,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦   -- Print_{0} --⏎
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦⏎
   --  ↦   procedure Print_{0} (
                 49 => Z'(First => 8012, Last => 8071,
                    Facility_Index => 2, Key_Index => 43,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 50 => Z'(First => 4727, Last => 4864,
                    Facility_Index => 5, Key_Index => 3,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      return Format (Facility ({0}), Key ({1}), Argumen⤶
   --  ↦ts,⏎
   --  ↦                     Locale => Locale, Catalog => Catal⤶
   --  ↦og);⏎
   --  ↦   end Format_{2};⏎
                 51 => Z'(First => 7108, Last => 7178,
                    Facility_Index => 1, Key_Index => 33,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, Error, Format not closed for key "{2}"⤶
   --  ↦ at position {3}
                 52 => Z'(First => 10065, Last => 10099,
                    Facility_Index => 2, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      & Wide_Character''Val ({0,*})
                 53 => Z'(First => 5401, Last => 5461,
                    Facility_Index => 6, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
                 54 => Z'(First => 3322, Last => 3492,
                    Facility_Index => 6, Key_Index => 4,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{0}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{0}Catalog_Type := Standard_Catalog)⤶
   --  ↦ return String⏎
   --  ↦   is⏎
   --  ↦      Arguments : Argument_List;⏎
   --  ↦   begin
                 55 => Z'(First => 6453, Last => 6526,
                    Facility_Index => 2, Key_Index => 24,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                    Locale_Index => {0,*}, Source_Local⤶
   --  ↦e_Index => {1,*}));
                 56 => Z'(First => 4727, Last => 4864,
                    Facility_Index => 6, Key_Index => 3,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      return Format (Facility ({0}), Key ({1}), Argumen⤶
   --  ↦ts,⏎
   --  ↦                     Locale => Locale, Catalog => Catal⤶
   --  ↦og);⏎
   --  ↦   end Format_{2};⏎
                 57 => Z'(First => 10297, Last => 10324,
                    Facility_Index => 2, Key_Index => 91,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦              others => <>);
                 58 => Z'(First => 2364, Last => 2571,
                    Facility_Index => 3, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Destination :{1}File_Type    := Current_Output;⏎
   --  ↦      With_NL     :{1}Boolean      := True;⏎
   --  ↦      Locale      :{1}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{1}Catalog_Type := Standard_Catalog)⤶
   --  ↦;
                 59 => Z'(First => 1991, Last => 2147,
                    Facility_Index => 7, Key_Index => 4,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{0}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{0}Catalog_Type := Standard_Catalog)⤶
   --  ↦⏎
   --  ↦   is⏎
   --  ↦      Arguments : Argument_List;⏎
   --  ↦   begin
                 60 => Z'(First => 5825, Last => 5899,
                    Facility_Index => 3, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Text_IO;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
                 61 => Z'(First => 4145, Last => 4293,
                    Facility_Index => 7, Key_Index => 14,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦   -- Raise_{0} --⏎
   --  ↦   ---------{1:-^{2,*}}---⏎
   --  ↦⏎
   --  ↦   procedure Raise_{0} (⏎
   --  ↦      E           :{3}Ada.Exceptions.Exception_Id;
                 62 => Z'(First => 7859, Last => 7889,
                    Facility_Index => 4, Key_Index => 89,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 63 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 3, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 64 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 4, Key_Index => 98,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 65 => Z'(First => 9955, Last => 9991,
                    Facility_Index => 4, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Argument{0,<3*} :{1}{2}''Class;
                 66 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 7, Key_Index => 94,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package body {0} is⏎
                 67 => Z'(First => 2364, Last => 2571,
                    Facility_Index => 4, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Destination :{1}File_Type    := Current_Output;⏎
   --  ↦      With_NL     :{1}Boolean      := True;⏎
   --  ↦      Locale      :{1}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{1}Catalog_Type := Standard_Catalog)⤶
   --  ↦;
                 68 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 5, Key_Index => 98,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 69 => Z'(First => 9402, Last => 9442,
                    Facility_Index => 1, Key_Index => 71,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0} errors detected, no sources generated
                 70 => Z'(First => 9685, Last => 9724,
                    Facility_Index => 1, Key_Index => 77,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, no source .properties files given
                 71 => Z'(First => 10417, Last => 10436,
                    Facility_Index => 5, Key_Index => 95,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}.{1}_Wide_Strings
                 72 => Z'(First => 10235, Last => 10267,
                    Facility_Index => 1, Key_Index => 17,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Output package spec file is "{0}"
                 73 => Z'(First => 6965, Last => 7036,
                    Facility_Index => 1, Key_Index => 31,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, Error, type mis-match for argument {2}⤶
   --  ↦: "{3}" and "{4}"
                 74 => Z'(First => 6839, Last => 6842,
                    Facility_Index => 1, Key_Index => 101,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}⏎
                 75 => Z'(First => 7643, Last => 7705,
                    Facility_Index => 1, Key_Index => 41,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, localized messages inconsistent with base locale⤶
   --  ↦ ("{0}")
                 76 => Z'(First => 7449, Last => 7513,
                    Facility_Index => 1, Key_Index => 38,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, invalid accessor type name value, "{0}", for the⤶
   --  ↦ -G option
                 77 => Z'(First => 8532, Last => 8586,
                    Facility_Index => 1, Key_Index => 55,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the facility "{0}" is not a valid Ada identifier⤶
                 78 => Z'(First => 5123, Last => 5251,
                    Facility_Index => 2, Key_Index => 17,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   function Standard_Catalog return ZanyBlue.Text.Catal⤶
   --  ↦ogs.Catalog_Type⏎
   --  ↦      renames ZanyBlue.Text.Formatting.Standard_Catalog⤶
   --  ↦;⏎
                 79 => Z'(First => 7037, Last => 7107,
                    Facility_Index => 2, Key_Index => 32,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   Pool : constant ZT.Static_Message_Pool_Type := Pool_⤶
   --  ↦Data_1''Access;⏎
                 80 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 6, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 81 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 2, Key_Index => 99,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 82 => Z'(First => 5401, Last => 5493,
                    Facility_Index => 6, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
   --  ↦   use ZanyBlue.Text.Arguments;⏎
                 83 => Z'(First => 9804, Last => 9841,
                    Facility_Index => 2, Key_Index => 80,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                   {0}_{1,*}''Access);
                 84 => Z'(First => 9955, Last => 9991,
                    Facility_Index => 3, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Argument{0,<3*} :{1}{2}''Class;
                 85 => Z'(First => 5717, Last => 5794,
                    Facility_Index => 7, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Exceptions;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
                 86 => Z'(First => 7351, Last => 7383,
                    Facility_Index => 3, Key_Index => 88,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 87 => Z'(First => 5494, Last => 5574,
                    Facility_Index => 3, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use Ada.Text_IO;⏎
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
                 88 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 7, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 89 => Z'(First => 5607, Last => 5686,
                    Facility_Index => 4, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Wide_Text_IO;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
                 90 => Z'(First => 9227, Last => 9271,
                    Facility_Index => 1, Key_Index => 68,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Retained accessor package spec "{0}" in "{1}"
                 91 => Z'(First => 10100, Last => 10133,
                    Facility_Index => 1, Key_Index => 85,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, failed to create "{0}": {1}
                 92 => Z'(First => 9880, Last => 9917,
                    Facility_Index => 1, Key_Index => 82,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Wrote the spec "{0}" to the file "{1}"
                 93 => Z'(First => 6216, Last => 6296,
                    Facility_Index => 1, Key_Index => 22,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Warning, no messages defined for the facility "{0}", no⤶
   --  ↦ accessor packages created
                 94 => Z'(First => 7951, Last => 8011,
                    Facility_Index => 1, Key_Index => 46,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Debug: Writing optimize catalog description to optimize⤶
   --  ↦d.dump
                 95 => Z'(First => 8364, Last => 8419,
                    Facility_Index => 1, Key_Index => 52,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the -a and -G options should not be used togethe⤶
   --  ↦r
                 96 => Z'(First => 8072, Last => 8131,
                    Facility_Index => 2, Key_Index => 47,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   Messages : constant ZTC.ZBMCompile_List (1 .. {0,*})⤶
   --  ↦ := (
                 97 => Z'(First => 6007, Last => 6030,
                    Facility_Index => 5, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   function Format_{0} (
                 98 => Z'(First => 2773, Last => 2966,
                    Facility_Index => 2, Key_Index => 7,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   procedure Initialize (⏎
   --  ↦      Catalog :{0}ZanyBlue.Text.Catalogs.Catalog_Type :⤶
   --  ↦= Standard_Catalog);⏎
   --  ↦   --  The catalog initialization routine: load the com⤶
   --  ↦piled messages into⏎
   --  ↦   --  a catalog.
                 99 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 2, Key_Index => 13,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 100 => Z'(First => 6747, Last => 6819,
                    Facility_Index => 2, Key_Index => 28,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                    Locale_Index => {0,*}, Source_Local⤶
   --  ↦e_Index => {1,*}),
                 101 => Z'(First => 5930, Last => 6030,
                    Facility_Index => 6, Key_Index => 14,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ----------{1:-^{2,*}}---⏎
   --  ↦   -- Format_{0} --⏎
   --  ↦   ----------{1:-^{2,*}}---⏎
   --  ↦⏎
   --  ↦   function Format_{0} (
                 102 => Z'(First => 9955, Last => 9991,
                    Facility_Index => 7, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Argument{0,<3*} :{1}{2}''Class;
                 103 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 6, Key_Index => 94,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package body {0} is⏎
                 104 => Z'(First => 7319, Last => 7383,
                    Facility_Index => 3, Key_Index => 36,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Arguments;⏎
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 105 => Z'(First => 5607, Last => 5716,
                    Facility_Index => 4, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with Ada.Wide_Text_IO;⏎
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
   --  ↦with ZanyBlue.Text.Arguments;⏎
                 106 => Z'(First => 7829, Last => 7889,
                    Facility_Index => 7, Key_Index => 44,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Arguments;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 107 => Z'(First => 6820, Last => 6892,
                    Facility_Index => 7, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   procedure Raise_{0}⏎
   --  ↦     (E           :{1}Ada.Exceptions.Exception_Id;
                 108 => Z'(First => 9645, Last => 9684,
                    Facility_Index => 3, Key_Index => 76,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Append (Arguments, Argument{0,*});
                 109 => Z'(First => 9181, Last => 9226,
                    Facility_Index => 1, Key_Index => 67,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Generated accessor package body "{0}" to "{1}"
                 110 => Z'(First => 9484, Last => 9524,
                    Facility_Index => 1, Key_Index => 73,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Retained the body "{0}" in the file "{1}"
                 111 => Z'(First => 7859, Last => 7889,
                    Facility_Index => 5, Key_Index => 89,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 112 => Z'(First => 6674, Last => 6746,
                    Facility_Index => 1, Key_Index => 27,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Skipping consistency checks for "{0}", base locale ("{1⤶
   --  ↦}") is not defined
                 113 => Z'(First => 3146, Last => 3321,
                    Facility_Index => 5, Key_Index => 4,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{0}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{0}Catalog_Type := Standard_Catalog)⤶
   --  ↦ return Wide_String⏎
   --  ↦   is⏎
   --  ↦      Arguments : Argument_List;⏎
   --  ↦   begin
                 114 => Z'(First => 5401, Last => 5461,
                    Facility_Index => 5, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
                 115 => Z'(First => 7179, Last => 7248,
                    Facility_Index => 1, Key_Index => 34,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Loaded total {0} characters, stored {1} unique characte⤶
   --  ↦rs, {2}% saving
                 116 => Z'(First => 8307, Last => 8363,
                    Facility_Index => 1, Key_Index => 51,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the name "{0}" does not name a valid sizing targ⤶
   --  ↦et
                 117 => Z'(First => 7829, Last => 7889,
                    Facility_Index => 5, Key_Index => 44,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Arguments;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 118 => Z'(First => 10532, Last => 10544,
                    Facility_Index => 2, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      & "{0}"
                 119 => Z'(First => 8642, Last => 8695,
                    Facility_Index => 1, Key_Index => 57,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0} errors detected, forcing generation of Ada sources
                 120 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 2, Key_Index => 42,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 121 => Z'(First => 8132, Last => 8190,
                    Facility_Index => 2, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   {0} : constant ZT.Constant_String_List (1 .. {1,*}) ⤶
   --  ↦:= (
                 122 => Z'(First => 1301, Last => 1619,
                    Facility_Index => 2, Key_Index => 2,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ----------------⏎
   --  ↦   -- Initialize --⏎
   --  ↦   ----------------⏎
   --  ↦⏎
   --  ↦   procedure Initialize (Catalog :{0}ZTC.Catalog_Type :⤶
   --  ↦= Standard_Catalog) is⏎
   --  ↦   begin⏎
   --  ↦      ZTC.Initialize (Catalog, Messages, Pool, Faciliti⤶
   --  ↦es, Keys, Locales,⏎
   --  ↦                      "{1}",⏎
   --  ↦                      Pool_Data_1''Length, {2});⏎
   --  ↦   end Initialize;⏎
                 123 => Z'(First => 10268, Last => 10296,
                    Facility_Index => 2, Key_Index => 90,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦begin  --  {0}⏎
   --  ↦   Initialize;
                 124 => Z'(First => 9645, Last => 9684,
                    Facility_Index => 6, Key_Index => 76,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Append (Arguments, Argument{0,*});
                 125 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 3, Key_Index => 94,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package body {0} is⏎
                 126 => Z'(First => 9645, Last => 9684,
                    Facility_Index => 7, Key_Index => 76,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Append (Arguments, Argument{0,*});
                 127 => Z'(First => 7351, Last => 7383,
                    Facility_Index => 4, Key_Index => 88,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 128 => Z'(First => 8997, Last => 9042,
                    Facility_Index => 1, Key_Index => 64,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the option ''{0}'' requires an argument
                 129 => Z'(First => 9842, Last => 9879,
                    Facility_Index => 1, Key_Index => 81,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Wrote the body "{0}" to the file "{1}"
                 130 => Z'(First => 9725, Last => 9764,
                    Facility_Index => 1, Key_Index => 78,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Loaded {0} messages(s) for {1} locale(s)
                 131 => Z'(First => 10456, Last => 10473,
                    Facility_Index => 7, Key_Index => 95,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}.{1}_Exceptions
                 132 => Z'(First => 5401, Last => 5493,
                    Facility_Index => 5, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
   --  ↦   use ZanyBlue.Text.Arguments;⏎
                 133 => Z'(First => 7706, Last => 7767,
                    Facility_Index => 1, Key_Index => 42,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦ZBMCompile completed at {0,time} on {0,date}, elapsed t⤶
   --  ↦ime {1}
                 134 => Z'(First => 1, Last => 1300,
                    Facility_Index => 1, Key_Index => 1,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Usage: zbmcompile [ options ] package facility⏎
   --  ↦where available options are⏎
   --  ↦  -q             Quiet mode⏎
   --  ↦  -v             Verbose mode⏎
   --  ↦  -m             Always include argument modes in gener⤶
   --  ↦ated code⏎
   --  ↦  -p             Number list entries (gnatcheck +RPosit⤶
   --  ↦ional_Components)⏎
   --  ↦  -D             Debug mode (dump the catalog definitio⤶
   --  ↦ns)⏎
   --  ↦  -d directory   Directory containing facility (default⤶
   --  ↦s to ".")⏎
   --  ↦  -e extension   Properties extension (default "propert⤶
   --  ↦ies")⏎
   --  ↦  -i             Include initialization call in body⏎
   --  ↦  -O             Optimize string pool for locale based ⤶
   --  ↦access⏎
   --  ↦  -g             Disable locale based access optimizati⤶
   --  ↦on (default)⏎
   --  ↦  -B             Compile only the base locale⏎
   --  ↦  -u             Disable consistency checked (unchecked⤶
   --  ↦ mode)⏎
   --  ↦  -L locale      Compile only the named locale, e.g., "⤶
   --  ↦fr", "fr_FR"⏎
   --  ↦  -r locale      Define reference (base) locale for con⤶
   --  ↦sistency checking⏎
   --  ↦  -s locale      Define source root locale⏎
   --  ↦  -S stamp-file  File to always create/update (contains⤶
   --  ↦ a timestamp)⏎
   --  ↦  -x name        Define external name for Initialize pr⤶
   --  ↦ocedure⏎
   --  ↦  -F             Force generation, ignoring errors.  Ge⤶
   --  ↦nerated code might⏎
   --  ↦                 not compile⏎
   --  ↦  -C             Disable comments on generated accessor⤶
   --  ↦ routines⏎
   --  ↦  -T item size   Set the size of an Ada output limit: p⤶
   --  ↦ool or comment
                 135 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 5, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 136 => Z'(First => 10325, Last => 10349,
                    Facility_Index => 1, Key_Index => 15,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦No files found to compile
                 137 => Z'(First => 9955, Last => 9991,
                    Facility_Index => 5, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Argument{0,<3*} :{1}{2}''Class;
                 138 => Z'(First => 8587, Last => 8641,
                    Facility_Index => 2, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   {0}_{1,*} : aliased constant Wide_String := "{2}"{3}⤶
                 139 => Z'(First => 7514, Last => 7578,
                    Facility_Index => 1, Key_Index => 39,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Performing consistency checks for the accessor package ⤶
   --  ↦generation
                 140 => Z'(First => 2572, Last => 2772,
                    Facility_Index => 2, Key_Index => 1,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --  Since the body calls the Initialize procedure, t⤶
   --  ↦his package need⏎
   --  ↦   --  only be with''ed.  Suppress any compiler warning⤶
   --  ↦s about an unused⏎
   --  ↦   --  with''ed package.⏎
   --  ↦   pragma Warnings (Off, {0});⏎
                 141 => Z'(First => 4994, Last => 5122,
                    Facility_Index => 2, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   package ZT  renames ZanyBlue.Text;⏎
   --  ↦   package ZTC renames ZanyBlue.Text.Catalogs;⏎
   --  ↦⏎
   --  ↦   subtype Z is ZTC.ZBMCompile_Definition;⏎
                 142 => Z'(First => 9918, Last => 9954,
                    Facility_Index => 2, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                   {0}_{1,*}''Access,
                 143 => Z'(First => 9955, Last => 9991,
                    Facility_Index => 6, Key_Index => 48,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Argument{0,<3*} :{1}{2}''Class;
                 144 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 6, Key_Index => 98,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 145 => Z'(First => 4584, Last => 4726,
                    Facility_Index => 7, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{1}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{1}Catalog_Type := Standard_Catalog)⤶
   --  ↦;⏎
   --  ↦   pragma No_Return (Raise_{0});
                 146 => Z'(First => 5494, Last => 5606,
                    Facility_Index => 3, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use Ada.Text_IO;⏎
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
   --  ↦   use ZanyBlue.Text.Arguments;⏎
                 147 => Z'(First => 3989, Last => 4144,
                    Facility_Index => 3, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada specification generated by ZBMCompile, V{0}.{1}⤶
   --  ↦.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 148 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 4, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 149 => Z'(First => 10134, Last => 10167,
                    Facility_Index => 1, Key_Index => 86,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, syntax error: {2}
                 150 => Z'(First => 7859, Last => 7889,
                    Facility_Index => 3, Key_Index => 89,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 151 => Z'(First => 10350, Last => 10374,
                    Facility_Index => 1, Key_Index => 92,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Stamp file created on {0}
                 152 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 3, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 153 => Z'(First => 7351, Last => 7383,
                    Facility_Index => 7, Key_Index => 88,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 154 => Z'(First => 9272, Last => 9316,
                    Facility_Index => 1, Key_Index => 69,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Retained accessor package body "{0}" in "{1}"
                 155 => Z'(First => 6377, Last => 6452,
                    Facility_Index => 1, Key_Index => 23,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Warning, the key "{0}" in the facility "{1}" is defined⤶
   --  ↦ for the locale "{2}"
                 156 => Z'(First => 3493, Last => 3662,
                    Facility_Index => 2, Key_Index => 9,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ---{2:-^{3,*}}----------⏎
   --  ↦   --- {0}_Count --⏎
   --  ↦   ---{2:-^{3,*}}----------⏎
   --  ↦⏎
   --  ↦   function {0}_Count return Natural is⏎
   --  ↦   begin⏎
   --  ↦      return {1}''Length;⏎
   --  ↦   end {0}_Count;⏎
                 157 => Z'(First => 8420, Last => 8475,
                    Facility_Index => 1, Key_Index => 53,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Loaded {0} messages for the facility "{1}" ({2} locales⤶
   --  ↦)
                 158 => Z'(First => 10489, Last => 10503,
                    Facility_Index => 6, Key_Index => 56,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦package {0} is⏎
                 159 => Z'(First => 10504, Last => 10514,
                    Facility_Index => 2, Key_Index => 97,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --  ↦{0}
                 160 => Z'(First => 9043, Last => 9088,
                    Facility_Index => 2, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                   {1,*} => {0}_{1,*}''Access,
                 161 => Z'(First => 7829, Last => 7889,
                    Facility_Index => 6, Key_Index => 44,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Arguments;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 162 => Z'(First => 5630, Last => 5686,
                    Facility_Index => 6, Key_Index => 16,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
                 163 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 6, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 164 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 2, Key_Index => 79,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 165 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 4, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 166 => Z'(First => 7859, Last => 7889,
                    Facility_Index => 6, Key_Index => 89,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 167 => Z'(First => 1301, Last => 1305,
                    Facility_Index => 2, Key_Index => 100,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --
                 168 => Z'(First => 1620, Last => 1892,
                    Facility_Index => 3, Key_Index => 3,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Write_Message (Destination, Facility ({0}), Key (⤶
   --  ↦{1}), Arguments,⏎
   --  ↦                     Format (Facility ({0}), Key ({1}),⤶
   --  ↦ Arguments,⏎
   --  ↦                             Locale => Locale, Catalog ⤶
   --  ↦=> Catalog),⏎
   --  ↦                     With_NL, Locale, Catalog);⏎
   --  ↦   end Print_{2};⏎
                 169 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 3, Key_Index => 12,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 170 => Z'(First => 6105, Last => 6128,
                    Facility_Index => 3, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   procedure Print_{0} (
                 171 => Z'(First => 5401, Last => 5493,
                    Facility_Index => 7, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
   --  ↦   use ZanyBlue.Text.Arguments;⏎
                 172 => Z'(First => 4440, Last => 4583,
                    Facility_Index => 7, Key_Index => 3,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Raise_Exception (E, Facility ({0}), Key ({1}), Ar⤶
   --  ↦guments,⏎
   --  ↦                       Locale => Locale, Catalog => Cat⤶
   --  ↦alog);⏎
   --  ↦   end Raise_{2};⏎
                 173 => Z'(First => 1620, Last => 1892,
                    Facility_Index => 4, Key_Index => 3,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Write_Message (Destination, Facility ({0}), Key (⤶
   --  ↦{1}), Arguments,⏎
   --  ↦                     Format (Facility ({0}), Key ({1}),⤶
   --  ↦ Arguments,⏎
   --  ↦                             Locale => Locale, Catalog ⤶
   --  ↦=> Catalog),⏎
   --  ↦                     With_NL, Locale, Catalog);⏎
   --  ↦   end Print_{2};⏎
                 174 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 3, Key_Index => 98,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 175 => Z'(First => 5376, Last => 5493,
                    Facility_Index => 4, Key_Index => 18,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use Ada.Wide_Text_IO;⏎
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
   --  ↦   use ZanyBlue.Text.Arguments;⏎
                 176 => Z'(First => 5376, Last => 5461,
                    Facility_Index => 4, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use Ada.Wide_Text_IO;⏎
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
                 177 => Z'(First => 9525, Last => 9564,
                    Facility_Index => 1, Key_Index => 74,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, failed to access the source "{0}"
                 178 => Z'(First => 7319, Last => 7383,
                    Facility_Index => 4, Key_Index => 36,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Arguments;⏎
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 179 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 7, Key_Index => 98,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 180 => Z'(First => 3823, Last => 3830,
                    Facility_Index => 7, Key_Index => 83,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦end {0};
                 181 => Z'(First => 6129, Last => 6215,
                    Facility_Index => 1, Key_Index => 20,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦"{0}", line {1}, Error, Illegal format for key "{2}", c⤶
   --  ↦haracter ''{3}'' at position {4}
                 182 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 4, Key_Index => 12,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 183 => Z'(First => 8853, Last => 8902,
                    Facility_Index => 1, Key_Index => 61,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, the key "{0}" is not a valid Ada identifier
                 184 => Z'(First => 8696, Last => 8749,
                    Facility_Index => 1, Key_Index => 58,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Suppressing base message comments on accessor routines
                 185 => Z'(First => 8802, Last => 8852,
                    Facility_Index => 2, Key_Index => 60,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦                 Z''(First => {1,*}, Last => {2,*},
                 186 => Z'(First => 7249, Last => 7318,
                    Facility_Index => 1, Key_Index => 35,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, no reference definition for the key "{0}" in the⤶
   --  ↦ facility "{1}"
                 187 => Z'(First => 2148, Last => 2363,
                    Facility_Index => 2, Key_Index => 5,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   ----------------⏎
   --  ↦   -- Initialize --⏎
   --  ↦   ----------------⏎
   --  ↦⏎
   --  ↦   procedure Initialize (Catalog :{0}ZTC.Catalog_Type :⤶
   --  ↦= Standard_Catalog) is⏎
   --  ↦      pragma Unreferenced (Catalog);⏎
   --  ↦   begin⏎
   --  ↦      null;⏎
   --  ↦   end Initialize;⏎
                 188 => Z'(First => 5252, Last => 5375,
                    Facility_Index => 6, Key_Index => 6,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Locale      :{1}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{1}Catalog_Type := Standard_Catalog)⤶
   --  ↦ return String;
                 189 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 2, Key_Index => 11,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 190 => Z'(First => 6007, Last => 6030,
                    Facility_Index => 6, Key_Index => 29,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   function Format_{0} (
                 191 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 6, Key_Index => 12,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 192 => Z'(First => 10375, Last => 10396,
                    Facility_Index => 2, Key_Index => 93,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   --  No base message
                 193 => Z'(First => 1893, Last => 2147,
                    Facility_Index => 3, Key_Index => 4,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Destination :{0}File_Type    := Current_Output;⏎
   --  ↦      With_NL     :{0}Boolean      := True;⏎
   --  ↦      Locale      :{0}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{0}Catalog_Type := Standard_Catalog)⤶
   --  ↦⏎
   --  ↦   is⏎
   --  ↦      Arguments : Argument_List;⏎
   --  ↦   begin
                 194 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 7, Key_Index => 12,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 195 => Z'(First => 7829, Last => 7889,
                    Facility_Index => 3, Key_Index => 44,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Arguments;⏎
   --  ↦with ZanyBlue.Text.Formatting;⏎
                 196 => Z'(First => 10437, Last => 10455,
                    Facility_Index => 4, Key_Index => 95,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}.{1}_Wide_Prints
                 197 => Z'(First => 9565, Last => 9604,
                    Facility_Index => 2, Key_Index => 74,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   pragma Export (C, Initialize, "{0}");
                 198 => Z'(First => 7319, Last => 7383,
                    Facility_Index => 7, Key_Index => 36,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Arguments;⏎
   --  ↦   use ZanyBlue.Text.Formatting;⏎
                 199 => Z'(First => 5401, Last => 5461,
                    Facility_Index => 7, Key_Index => 21,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦   use ZanyBlue.Text.Catalogs;⏎
   --  ↦   use ZanyBlue.Text.Locales;⏎
                 200 => Z'(First => 10518, Last => 10531,
                    Facility_Index => 3, Key_Index => 95,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦{0}.{1}_Prints
                 201 => Z'(First => 1893, Last => 2147,
                    Facility_Index => 4, Key_Index => 4,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦      Destination :{0}File_Type    := Current_Output;⏎
   --  ↦      With_NL     :{0}Boolean      := True;⏎
   --  ↦      Locale      :{0}Locale_Type  := Current_Locale;⏎
   --  ↦      Catalog     :{0}Catalog_Type := Standard_Catalog)⤶
   --  ↦⏎
   --  ↦   is⏎
   --  ↦      Arguments : Argument_List;⏎
   --  ↦   begin
                 202 => Z'(First => 9089, Last => 9134,
                    Facility_Index => 1, Key_Index => 65,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Generated accessor package spec "{0}" to "{1}"
                 203 => Z'(First => 9765, Last => 9803,
                    Facility_Index => 1, Key_Index => 79,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Bootstrap loaded {0} messages for "{1}"
                 204 => Z'(First => 3832, Last => 3988,
                    Facility_Index => 5, Key_Index => 12,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦--  -*- encoding: utf-8 -*-⏎
   --  ↦--⏎
   --  ↦--  Ada implementation generated by ZBMCompile, V{0}.{1⤶
   --  ↦}.{2} - {3}.⏎
   --  ↦--  This is a generated file and should not be edited.⏎⤶
   --  ↦--⏎
                 205 => Z'(First => 10202, Last => 10234,
                    Facility_Index => 1, Key_Index => 8,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Output package body file is "{0}"
                 206 => Z'(First => 6527, Last => 6600,
                    Facility_Index => 1, Key_Index => 25,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Error, too many arguments for key "{0}" in facility "{1⤶
   --  ↦}" for locale "{2}"
                 207 => Z'(First => 5630, Last => 5716,
                    Facility_Index => 5, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦with ZanyBlue.Text.Catalogs;⏎
   --  ↦with ZanyBlue.Text.Locales;⏎
   --  ↦with ZanyBlue.Text.Arguments;⏎
                 208 => Z'(First => 7768, Last => 7828,
                    Facility_Index => 1, Key_Index => 43,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Copyright (c) 2009-{0,*}, Michael Rohan.  All rights re⤶
   --  ↦served
                 209 => Z'(First => 8191, Last => 8248,
                    Facility_Index => 1, Key_Index => 49,
                    Locale_Index => 1, Source_Locale_Index => 1),
   --  ↦Created the stamp file "{0}" containing the time stamp ⤶
   --  ↦{1}
                 210 => Z'(First => 10397, Last => 10416,
                    Facility_Index => 2, Key_Index => 19,
                    Locale_Index => 1, Source_Locale_Index => 1));
   --  ↦package body {0} is⏎

   ---------------
   --- Facility --
   ---------------

   function Facility (Index : in Positive) return Wide_String is
   begin
      return Facilities (Index).all;
   end Facility;

   ---------------------
   --- Facility_Count --
   ---------------------

   function Facility_Count return Natural is
   begin
      return Facilities'Length;
   end Facility_Count;

   ----------------
   -- Initialize --
   ----------------

   procedure Initialize (Catalog : in ZTC.Catalog_Type := Standard_Catalog) is
   begin
      ZTC.Initialize (Catalog, Messages, Pool, Facilities, Keys, Locales,
                      "ZBMCompile.Messages",
                      Pool_Data_1'Length, 10555);
   end Initialize;

   ----------
   --- Key --
   ----------

   function Key (Index : in Positive) return Wide_String is
   begin
      return Keys (Index).all;
   end Key;

   ----------------
   --- Key_Count --
   ----------------

   function Key_Count return Natural is
   begin
      return Keys'Length;
   end Key_Count;

end ZBMCompile.Messages;
