--  -*- encoding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile
--  This is a generated file and should not be edited.
--

package body ZBMCompile.Messages is

   subtype Z is ZTC.ZBMCompile_Definition;

   Key_1 : aliased constant Wide_String := "00001";
   Key_2 : aliased constant Wide_String := "00002";
   Key_3 : aliased constant Wide_String := "00003";
   Key_4 : aliased constant Wide_String := "00004";
   Key_5 : aliased constant Wide_String := "00005";
   Key_6 : aliased constant Wide_String := "00006";
   Key_7 : aliased constant Wide_String := "00007";
   Key_8 : aliased constant Wide_String := "00008";
   Key_9 : aliased constant Wide_String := "00009";
   Key_10 : aliased constant Wide_String := "00010";
   Key_11 : aliased constant Wide_String := "00011";
   Key_12 : aliased constant Wide_String := "00012";
   Key_13 : aliased constant Wide_String := "00013";
   Key_14 : aliased constant Wide_String := "00014";
   Key_15 : aliased constant Wide_String := "00015";
   Key_16 : aliased constant Wide_String := "00016";
   Key_17 : aliased constant Wide_String := "00017";
   Key_18 : aliased constant Wide_String := "00018";
   Key_19 : aliased constant Wide_String := "00019";
   Key_20 : aliased constant Wide_String := "00020";
   Key_21 : aliased constant Wide_String := "00021";
   Key_22 : aliased constant Wide_String := "00022";
   Key_23 : aliased constant Wide_String := "00023";
   Key_24 : aliased constant Wide_String := "00024";
   Key_25 : aliased constant Wide_String := "00025";
   Key_26 : aliased constant Wide_String := "00026";
   Key_27 : aliased constant Wide_String := "10000";
   Key_28 : aliased constant Wide_String := "10001";
   Key_29 : aliased constant Wide_String := "10002";
   Key_30 : aliased constant Wide_String := "10003";
   Key_31 : aliased constant Wide_String := "10004";
   Key_32 : aliased constant Wide_String := "10005";
   Key_33 : aliased constant Wide_String := "10006";
   Key_34 : aliased constant Wide_String := "10007";
   Key_35 : aliased constant Wide_String := "10008";
   Key_36 : aliased constant Wide_String := "10009";
   Key_37 : aliased constant Wide_String := "10010";
   Key_38 : aliased constant Wide_String := "10011";
   Key_39 : aliased constant Wide_String := "10012";
   Key_40 : aliased constant Wide_String := "10013";
   Key_41 : aliased constant Wide_String := "10014";
   Key_42 : aliased constant Wide_String := "10015";
   Key_43 : aliased constant Wide_String := "10016";
   Key_44 : aliased constant Wide_String := "10017";
   Key_45 : aliased constant Wide_String := "10018";
   Key_46 : aliased constant Wide_String := "10019";
   Key_47 : aliased constant Wide_String := "10020";
   Key_48 : aliased constant Wide_String := "10021";
   Key_49 : aliased constant Wide_String := "10022";
   Key_50 : aliased constant Wide_String := "20000";
   Key_51 : aliased constant Wide_String := "20001";
   Key_52 : aliased constant Wide_String := "20002";
   Key_53 : aliased constant Wide_String := "20003";
   Key_54 : aliased constant Wide_String := "20004";
   Key_55 : aliased constant Wide_String := "20005";
   Key_56 : aliased constant Wide_String := "20006";
   Key_57 : aliased constant Wide_String := "20007";
   Key_58 : aliased constant Wide_String := "20008";
   Key_59 : aliased constant Wide_String := "20009";
   Key_60 : aliased constant Wide_String := "20010";
   Key_61 : aliased constant Wide_String := "20011";
   Key_62 : aliased constant Wide_String := "20012";
   Key_63 : aliased constant Wide_String := "20013";
   Key_64 : aliased constant Wide_String := "20014";
   Key_65 : aliased constant Wide_String := "20015";
   Key_66 : aliased constant Wide_String := "20016";
   Key_67 : aliased constant Wide_String := "20017";
   Key_68 : aliased constant Wide_String := "20018";
   Key_69 : aliased constant Wide_String := "20019";
   Key_70 : aliased constant Wide_String := "20020";
   Key_71 : aliased constant Wide_String := "20021";
   Key_72 : aliased constant Wide_String := "20022";
   Key_73 : aliased constant Wide_String := "20023";
   Key_74 : aliased constant Wide_String := "20024";
   Key_75 : aliased constant Wide_String := "20025";
   Key_76 : aliased constant Wide_String := "20026";
   Key_77 : aliased constant Wide_String := "20027";
   Key_78 : aliased constant Wide_String := "20028";
   Key_79 : aliased constant Wide_String := "20029";
   Key_80 : aliased constant Wide_String := "20030";
   Key_81 : aliased constant Wide_String := "20031";
   Key_82 : aliased constant Wide_String := "20032";
   Key_83 : aliased constant Wide_String := "20033";
   Keys : constant ZT.Constant_String_List (1 .. 83) := (
              Key_1'Access,
              Key_2'Access,
              Key_3'Access,
              Key_4'Access,
              Key_5'Access,
              Key_6'Access,
              Key_7'Access,
              Key_8'Access,
              Key_9'Access,
              Key_10'Access,
              Key_11'Access,
              Key_12'Access,
              Key_13'Access,
              Key_14'Access,
              Key_15'Access,
              Key_16'Access,
              Key_17'Access,
              Key_18'Access,
              Key_19'Access,
              Key_20'Access,
              Key_21'Access,
              Key_22'Access,
              Key_23'Access,
              Key_24'Access,
              Key_25'Access,
              Key_26'Access,
              Key_27'Access,
              Key_28'Access,
              Key_29'Access,
              Key_30'Access,
              Key_31'Access,
              Key_32'Access,
              Key_33'Access,
              Key_34'Access,
              Key_35'Access,
              Key_36'Access,
              Key_37'Access,
              Key_38'Access,
              Key_39'Access,
              Key_40'Access,
              Key_41'Access,
              Key_42'Access,
              Key_43'Access,
              Key_44'Access,
              Key_45'Access,
              Key_46'Access,
              Key_47'Access,
              Key_48'Access,
              Key_49'Access,
              Key_50'Access,
              Key_51'Access,
              Key_52'Access,
              Key_53'Access,
              Key_54'Access,
              Key_55'Access,
              Key_56'Access,
              Key_57'Access,
              Key_58'Access,
              Key_59'Access,
              Key_60'Access,
              Key_61'Access,
              Key_62'Access,
              Key_63'Access,
              Key_64'Access,
              Key_65'Access,
              Key_66'Access,
              Key_67'Access,
              Key_68'Access,
              Key_69'Access,
              Key_70'Access,
              Key_71'Access,
              Key_72'Access,
              Key_73'Access,
              Key_74'Access,
              Key_75'Access,
              Key_76'Access,
              Key_77'Access,
              Key_78'Access,
              Key_79'Access,
              Key_80'Access,
              Key_81'Access,
              Key_82'Access,
              Key_83'Access);

   Locale_1 : aliased constant Wide_String := "";
   Locales : constant ZT.Constant_String_List (1 .. 1) := (
                 1 => Locale_1'Access);
   Pool_Data : aliased constant Wide_String := ""
      & "This is ZBMCompile, Version {0}.{1}.{2} {3} (r{4}) at {5,ti"
      & "me} on {5,date}Copyright (c) 2009-{0}, Michael Rohan.  All "
      & "rights reservedZBMCompile completed at {0,time} on {0,date}"
      & ", elapsed time {1}Usage: zbmcompile [ options ] package fac"
      & "ility"
      & Wide_Character'Val (10)
      & "where available options are"
      & Wide_Character'Val (10)
      & "  -q             Quiet mode"
      & Wide_Character'Val (10)
      & "  -v             Verbose mode"
      & Wide_Character'Val (10)
      & "  -D             Debug mode (dump the catalog definitions)"
      & Wide_Character'Val (10)
      & "  -d directory   Directory containing facility (defaults to"
      & " ""."")"
      & Wide_Character'Val (10)
      & "  -e extension   Properties extension (default .properties)"
      & Wide_Character'Val (10)
      & "  -i             Include initialization call in body"
      & Wide_Character'Val (10)
      & "  -O             Optimize string pool for locale based acce"
      & "ss"
      & Wide_Character'Val (10)
      & "  -g             Disable locale based access optimization ("
      & "default)"
      & Wide_Character'Val (10)
      & "  -B             Compile only the base locale"
      & Wide_Character'Val (10)
      & "  -L locale      Compile only the named locale, e.g., ""fr"""
      & ", ""fr_FR"""
      & Wide_Character'Val (10)
      & "  -s spec-file   Define name for spec file (defaults to GNA"
      & "T convention)"
      & Wide_Character'Val (10)
      & "  -b body-file   Define name for body file (defaults to GNA"
      & "T convention)"
      & Wide_Character'Val (10)
      & "  -x name        Define external name for Initialize proced"
      & "ure"
      & Wide_Character'Val (10)
      & "  -F             Force generation, ignoring errors.  Genera"
      & "ted code might"
      & Wide_Character'Val (10)
      & "                 not compileLoaded {0} messages(s) for {1} "
      & "locale(s)Output package spec file is ""{0}""Output package "
      & "body file is ""{0}""No files found to compileWriting messag"
      & "es for the locale ""{0}"" ({1})Error, failed to access the "
      & "source ""{0}""Bootstrap loaded {0} messages for ""{1}""Load"
      & "ed {0} messages for the facility ""{1}"" ({2} locales)""{0}"
      & """, line {1}, syntax error: {2}""{0}"", line {1}, duplicate"
      & " key ""{2}"" previous defined on line {3}Error, no messages"
      & " files processedError, the option ''{0}'' requires an argum"
      & "entError, a package name argument is requiredError, no sour"
      & "ce .properties files given{0}"
      & Wide_Character'Val (10)
      & "Loaded {0} facilities, {1} keys, {2} locales and {3} messag"
      & "esWrote the spec ""{0}"" to the file ""{1}""Wrote the body "
      & """{0}"" to the file ""{1}""Optimizing the catalog for local"
      & "e order accessCollected the messages for the locale ""{0}"""
      & " ({1} messages, {2} characters){0} errors detected, no sour"
      & "ces generated{0} errors detected, forcing generation of Ada"
      & " sources--  -*- encoding: utf-8 -*-----  Ada specification "
      & "generated by ZBMCompile.--  This is a generated file and sh"
      & "ould not be edited.--with ZanyBlue.Text.Catalogs;with ZanyB"
      & "lue.Text.Formatting;package {0} is   --  Since the body cal"
      & "ls the Initialize procedure, this package need   --  only b"
      & "e with''ed.  Suppress any compiler warnings about an unused"
      & "   --  with''ed package.   pragma Warnings (Off, {0});   pa"
      & "ckage ZT  renames ZanyBlue.Text;   package ZTC renames Zany"
      & "Blue.Text.Catalogs;   package ZTF renames ZanyBlue.Text.For"
      & "matting;   Facility_{0} : aliased constant Wide_String := """
      & "{1}""{2}   Facilities : constant ZT.Constant_String_List (1"
      & " .. {0}) := (                   Facility_{0}''Access,      "
      & "             1 => Facility_1''Access);                   Fa"
      & "cility_{0}''Access);   procedure Initialize (Catalog : ZTC."
      & "Catalog_Type := ZTF.Standard_Catalog);   pragma Export (C, "
      & "Initialize, ""{0}"");end {0};--  -*- encoding: utf-8 -*----"
      & "-  Ada implementation generated by ZBMCompile--  This is a "
      & "generated file and should not be edited.--package body {0} "
      & "is   subtype Z is ZTC.ZBMCompile_Definition;   Key_{0} : al"
      & "iased constant Wide_String := ""{1}""{2}   Keys : constant "
      & "ZT.Constant_String_List (1 .. {0}) := (              Key_{0"
      & "}''Access,              1 => Key_''Access);              Ke"
      & "y_{0}''Access);   Locale_{0} : aliased constant Wide_String"
      & " := ""{1}"";   Locales : constant ZT.Constant_String_List ("
      & "1 .. {0}) := (                 Locale_{0}''Access,         "
      & "        1 => Locale_1''Access);                 Locale_{0}'"
      & "'Access);   Pool_Data : aliased constant Wide_String := ""{"
      & "1}""{2}      & Wide_Character''Val ({0})      & ""{0}""    "
      & "  & """";   Pool : constant ZT.Static_Message_Pool_Type := "
      & "Pool_Data''Access;   Messages : constant ZTC.ZBMCompile_Lis"
      & "t (1 .. {0}) := (                 1 => Z''({0}, {1}, {2}, {"
      & "3}, {4}));                 Z''({0}, {1}, {2}, {3}, {4}),   "
      & "              Z''({0}, {1}, {2}, {3}, {4}));   procedure In"
      & "itialize (Catalog : ZTC.Catalog_Type := ZTF.Standard_Catalo"
      & "g) is   begin      ZTC.Initialize (Catalog, Messages, Pool,"
      & " Facilities, Keys, Locales);      null;   end Initialize;be"
      & "gin   Initialize;end {0};"
      & "";
   Pool : constant ZT.Static_Message_Pool_Type := Pool_Data'Access;

   Messages : constant ZTC.ZBMCompile_List (1 .. 83) := (
                 Z'(2, 28, 1, 2074, 2075),
                 Z'(2, 39, 1, 2447, 2483),
                 Z'(1, 21, 1, 1756, 1793),
                 Z'(1, 13, 1, 1430, 1463),
                 Z'(1, 1, 1, 1, 74),
                 Z'(1, 10, 1, 1295, 1334),
                 Z'(2, 57, 1, 3142, 3194),
                 Z'(2, 76, 1, 3958, 4036),
                 Z'(2, 67, 1, 3575, 3629),
                 Z'(2, 54, 1, 3079, 3080),
                 Z'(2, 49, 1, 2942, 2949),
                 Z'(2, 34, 1, 2236, 2249),
                 Z'(2, 45, 1, 2740, 2783),
                 Z'(2, 37, 1, 2393, 2416),
                 Z'(1, 16, 1, 1563, 1608),
                 Z'(1, 19, 1, 1691, 1694),
                 Z'(1, 7, 1, 1194, 1226),
                 Z'(1, 8, 1, 1227, 1251),
                 Z'(2, 82, 1, 4153, 4166),
                 Z'(2, 73, 1, 3813, 3864),
                 Z'(2, 60, 1, 3283, 3315),
                 Z'(2, 74, 1, 3865, 3910),
                 Z'(2, 70, 1, 3676, 3686),
                 Z'(2, 65, 1, 3498, 3537),
                 Z'(2, 52, 1, 2979, 3024),
                 Z'(2, 43, 1, 2636, 2699),
                 Z'(2, 32, 1, 2178, 2205),
                 Z'(2, 31, 1, 2176, 2177),
                 Z'(1, 25, 1, 1952, 1992),
                 Z'(1, 22, 1, 1794, 1831),
                 Z'(1, 5, 1, 1121, 1160),
                 Z'(1, 14, 1, 1464, 1528),
                 Z'(1, 2, 1, 75, 133),
                 Z'(2, 80, 1, 4130, 4147),
                 Z'(2, 58, 1, 3195, 3252),
                 Z'(2, 79, 1, 4119, 4129),
                 Z'(2, 68, 1, 3630, 3662),
                 Z'(2, 50, 1, 2950, 2976),
                 Z'(2, 41, 1, 2530, 2577),
                 Z'(2, 46, 1, 2784, 2824),
                 Z'(2, 38, 1, 2417, 2446),
                 Z'(2, 29, 1, 2076, 2121),
                 Z'(1, 20, 1, 1695, 1755),
                 Z'(1, 12, 1, 1374, 1429),
                 Z'(1, 11, 1, 1335, 1373),
                 Z'(2, 56, 1, 3100, 3141),
                 Z'(2, 63, 1, 3401, 3461),
                 Z'(2, 77, 1, 4037, 4044),
                 Z'(2, 66, 1, 3538, 3574),
                 Z'(2, 48, 1, 2902, 2941),
                 Z'(2, 55, 1, 3081, 3099),
                 Z'(2, 44, 1, 2700, 2739),
                 Z'(2, 35, 1, 2250, 2320),
                 Z'(2, 36, 1, 2321, 2392),
                 Z'(2, 27, 1, 2047, 2073),
                 Z'(1, 26, 1, 1993, 2046),
                 Z'(1, 17, 1, 1609, 1650),
                 Z'(1, 18, 1, 1651, 1690),
                 Z'(1, 9, 1, 1252, 1294),
                 Z'(1, 6, 1, 1161, 1193),
                 Z'(2, 83, 1, 4167, 4174),
                 Z'(2, 72, 1, 3755, 3812),
                 Z'(2, 61, 1, 3316, 3346),
                 Z'(2, 75, 1, 3911, 3957),
                 Z'(2, 64, 1, 3462, 3497),
                 Z'(2, 62, 1, 3347, 3400),
                 Z'(2, 71, 1, 3687, 3754),
                 Z'(2, 42, 1, 2578, 2635),
                 Z'(2, 53, 1, 3025, 3078),
                 Z'(2, 33, 1, 2206, 2235),
                 Z'(2, 30, 1, 2122, 2175),
                 Z'(1, 23, 1, 1832, 1877),
                 Z'(1, 24, 1, 1878, 1951),
                 Z'(1, 15, 1, 1529, 1562),
                 Z'(1, 4, 1, 196, 1120),
                 Z'(1, 3, 1, 134, 195),
                 Z'(2, 81, 1, 4148, 4152),
                 Z'(2, 59, 1, 3253, 3282),
                 Z'(2, 78, 1, 4045, 4118),
                 Z'(2, 69, 1, 3663, 3675),
                 Z'(2, 40, 1, 2484, 2529),
                 Z'(2, 51, 1, 2977, 2978),
                 Z'(2, 47, 1, 2825, 2901));

   procedure Initialize (Catalog : ZTC.Catalog_Type := ZTF.Standard_Catalog) is
   begin
      ZTC.Initialize (Catalog, Messages, Pool, Facilities, Keys, Locales);
   end Initialize;

begin
   Initialize;
end ZBMCompile.Messages;
