# -*- coding: utf-8 -*-
# Copyright (c) 2016, Michael Rohan <mrohan@zanyblue.com>
# All rights reserved.
#
# This file was generated based on the comments in the ZBTest function
# implementation files (.adb files).
#


Dirname_Usage=Usage: dirname path
Dirname_Summary={0:>3}) "dirname", return directory component of a path
Dirname_Docstring=dirname: return directory component of a path\n\
\n\
\    Usage: dirname path\n\
\n\
The "dirname" function takes a path as an argument and returns the\n\
containing directory.  It is used in the zbmcompile tests to determine the\n\
installation directory for the zbmcompile executable, e.g.,::\n\
\n\
\    ZBTest> set project_dir $(dirname $(dirname $(which zbmcompile)))\n

Joinpaths_Usage=Usage: joinpaths path ...
Joinpaths_Summary={0:>3}) "joinpaths", return a list of path concatenated into a single path
Joinpaths_Docstring=joinpaths: return a list of path concatenated into a single path\n\
\n\
\    Usage: joinpaths path ...\n\
\n\
The "joinpaths" function takes one or more path components and combines\n\
them into a single path, e.g.,::\n\
\n\
\    ZBTest> set libdir $(joinpaths $project_dir lib)

Nextlog_Usage=Usage: nextlog [ -c counter ] [ -n ]
Nextlog_Summary={0:>3}) "nextlog", return the name of next number log file
Nextlog_Docstring=nextlog: return the name of next number log file\n\
\n\
\    Usage: nextlog [ -c counter ] [ -n ]\n\
\n\
The "nextlog" function returns the next log name for the current test\n\
based on a sequence controlled by the "_lognum" parameter.  By default,\n\
an undo action is also created to compare the generated log name with a\n\
reference log file on exiting the test scope.  The undo action creation\n\
is suppressed if the "-n" option is given.  The format of the log file\n\
name generated is::\n\
\n\
\    TESTNAME-nn.log\n\
\n\
where "TESTNAME" is the name of the current test and "nn" the sequence\n\
number.  The use of the "nextlog" function can simplify test scripts,\n\
e.g.,::\n\
\n\
\    execute -o mytest-01.log mycmd1\n\
\    execute -o mytest-02.log mycmd2\n\
\    compare mytest-01.log\n\
\    compare mytest-02.log\n\
\n\
can be re-written as::\n\
\n\
\    execute -o $(nextlog) mycmd1\n\
\    execute -o $(nextlog) mycmd2\n\
\n\
The "-c" option can be used to start a new log naming sequence for log\n\
files that are not part of the normal test reference logs, e.g., the output\n\
of the build commands to generate an executable are too platform specific\n\
to to be used as reference log files but the output should be stored in a\n\
log file for debugging.  The argument to the "-c" option is the name of\n\
an integer parameter which is used to sequence the log file name (the\n\
parameter is created if it does not already exist in the current scope).\n\
\n\
By default, log file using alternative counter names do not create\n\
undo actions to execute the compare command.  If the log files should\n\
be compared on scope exit, the "-n" option can be used.\n\
\n\
For example, save the output of a build command::\n\
\n\
\    execute -o $(nextlog -c build) build.sh\n\
\n\
would generate the log file TESTNAME-build-nn.log, the counter name\n\
is embedded in the log file.

Which_Usage=Usage: which [ -f | -e ] filename
Which_Summary={0:>3}) "which", return the path to a file or executable
Which_Docstring=which: return the path to a file or executable\n\
\n\
\    Usage: which [ -f | -e ] filename\n\
\n\
The "which" function returns the path to a file searched on the\n\
"searchpath" list, using the "-f" option (the default) or an executable\n\
on the "path" list, using the "-e" option.\n\
\n\
The "which" function is primarily used to determine where applications are\n\
installed with the result normally processed by the "dirname" function to\n\
to determine the parent directory, e.g.::\n\
\n\
\    ZBTest> set project_dir $(dirname $(dirname $(which zbmcompile)))\n\
\n\
where "project_dir" is set to "/usr" for an installed "zbmcompile"\n\
located at "/usr/bin/zbmcompile".
