--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Functions_Strings is

   use ZanyBlue.Text.Formatting;

   ------------------------------
   -- Format_Dirname_Docstring --
   ------------------------------

   function Format_Dirname_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (21),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Dirname_Docstring;

   ----------------------------
   -- Format_Dirname_Summary --
   ----------------------------

   function Format_Dirname_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (2), Key (64),
                     Arguments, Locale, Catalog);
   end Format_Dirname_Summary;

   --------------------------
   -- Format_Dirname_Usage --
   --------------------------

   function Format_Dirname_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (159),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Dirname_Usage;

   --------------------------------
   -- Format_Joinpaths_Docstring --
   --------------------------------

   function Format_Joinpaths_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (23),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Joinpaths_Docstring;

   ------------------------------
   -- Format_Joinpaths_Summary --
   ------------------------------

   function Format_Joinpaths_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (2), Key (33),
                     Arguments, Locale, Catalog);
   end Format_Joinpaths_Summary;

   ----------------------------
   -- Format_Joinpaths_Usage --
   ----------------------------

   function Format_Joinpaths_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (149),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Joinpaths_Usage;

   ------------------------------
   -- Format_Nextlog_Docstring --
   ------------------------------

   function Format_Nextlog_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (2),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Nextlog_Docstring;

   ----------------------------
   -- Format_Nextlog_Summary --
   ----------------------------

   function Format_Nextlog_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (2), Key (62),
                     Arguments, Locale, Catalog);
   end Format_Nextlog_Summary;

   --------------------------
   -- Format_Nextlog_Usage --
   --------------------------

   function Format_Nextlog_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (122),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Nextlog_Usage;

   ----------------------------
   -- Format_Which_Docstring --
   ----------------------------

   function Format_Which_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (13),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Which_Docstring;

   --------------------------
   -- Format_Which_Summary --
   --------------------------

   function Format_Which_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (2), Key (63),
                     Arguments, Locale, Catalog);
   end Format_Which_Summary;

   ------------------------
   -- Format_Which_Usage --
   ------------------------

   function Format_Which_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (2), Key (129),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Which_Usage;

end ZBTest_Messages.Functions_Strings;
