--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Commands_Prints is

   use ZanyBlue.Text.Formatting;

   ----------------------------
   -- Print_Append_Docstring --
   ----------------------------

   procedure Print_Append_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (12), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Append_Docstring;

   --------------------------
   -- Print_Append_Summary --
   --------------------------

   procedure Print_Append_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (74), Arguments, With_NL, Locale,
         Catalog);
   end Print_Append_Summary;

   ------------------------
   -- Print_Append_Usage --
   ------------------------

   procedure Print_Append_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (138), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Append_Usage;

   ---------------------------
   -- Print_Begin_Docstring --
   ---------------------------

   procedure Print_Begin_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (8), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Begin_Docstring;

   -------------------------
   -- Print_Begin_Summary --
   -------------------------

   procedure Print_Begin_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (96), Arguments, With_NL, Locale,
         Catalog);
   end Print_Begin_Summary;

   -----------------------
   -- Print_Begin_Usage --
   -----------------------

   procedure Print_Begin_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (173), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Begin_Usage;

   -----------------------------
   -- Print_Compare_Docstring --
   -----------------------------

   procedure Print_Compare_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (18), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Compare_Docstring;

   ---------------------------
   -- Print_Compare_Summary --
   ---------------------------

   procedure Print_Compare_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (60), Arguments, With_NL, Locale,
         Catalog);
   end Print_Compare_Summary;

   -------------------------
   -- Print_Compare_Usage --
   -------------------------

   procedure Print_Compare_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (109), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Compare_Usage;

   --------------------------
   -- Print_Copy_Docstring --
   --------------------------

   procedure Print_Copy_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (6), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Copy_Docstring;

   ------------------------
   -- Print_Copy_Summary --
   ------------------------

   procedure Print_Copy_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (97), Arguments, With_NL, Locale,
         Catalog);
   end Print_Copy_Summary;

   ----------------------
   -- Print_Copy_Usage --
   ----------------------

   procedure Print_Copy_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (143), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Copy_Usage;

   ----------------------------
   -- Print_Delenv_Docstring --
   ----------------------------

   procedure Print_Delenv_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (17), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Delenv_Docstring;

   --------------------------
   -- Print_Delenv_Summary --
   --------------------------

   procedure Print_Delenv_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (82), Arguments, With_NL, Locale,
         Catalog);
   end Print_Delenv_Summary;

   ------------------------
   -- Print_Delenv_Usage --
   ------------------------

   procedure Print_Delenv_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (160), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Delenv_Usage;

   ----------------------------
   -- Print_Delete_Docstring --
   ----------------------------

   procedure Print_Delete_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (27), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Delete_Docstring;

   --------------------------
   -- Print_Delete_Summary --
   --------------------------

   procedure Print_Delete_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (79), Arguments, With_NL, Locale,
         Catalog);
   end Print_Delete_Summary;

   ------------------------
   -- Print_Delete_Usage --
   ------------------------

   procedure Print_Delete_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (150), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Delete_Usage;

   --------------------------
   -- Print_Desc_Docstring --
   --------------------------

   procedure Print_Desc_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (30), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Desc_Docstring;

   ------------------------
   -- Print_Desc_Summary --
   ------------------------

   procedure Print_Desc_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (87), Arguments, With_NL, Locale,
         Catalog);
   end Print_Desc_Summary;

   ----------------------
   -- Print_Desc_Usage --
   ----------------------

   procedure Print_Desc_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (158), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Desc_Usage;

   --------------------------
   -- Print_Dump_Docstring --
   --------------------------

   procedure Print_Dump_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (22), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Dump_Docstring;

   ------------------------
   -- Print_Dump_Summary --
   ------------------------

   procedure Print_Dump_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (58), Arguments, With_NL, Locale,
         Catalog);
   end Print_Dump_Summary;

   ----------------------
   -- Print_Dump_Usage --
   ----------------------

   procedure Print_Dump_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (117), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Dump_Usage;

   --------------------------
   -- Print_Echo_Docstring --
   --------------------------

   procedure Print_Echo_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (24), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Echo_Docstring;

   ------------------------
   -- Print_Echo_Summary --
   ------------------------

   procedure Print_Echo_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (107), Arguments, With_NL, Locale,
         Catalog);
   end Print_Echo_Summary;

   ----------------------
   -- Print_Echo_Usage --
   ----------------------

   procedure Print_Echo_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (157), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Echo_Usage;

   -------------------------
   -- Print_End_Docstring --
   -------------------------

   procedure Print_End_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (11), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_End_Docstring;

   -----------------------
   -- Print_End_Summary --
   -----------------------

   procedure Print_End_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (50), Arguments, With_NL, Locale,
         Catalog);
   end Print_End_Summary;

   ---------------------
   -- Print_End_Usage --
   ---------------------

   procedure Print_End_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (177), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_End_Usage;

   -----------------------------
   -- Print_Execute_Docstring --
   -----------------------------

   procedure Print_Execute_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (1), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Execute_Docstring;

   ---------------------------
   -- Print_Execute_Summary --
   ---------------------------

   procedure Print_Execute_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (98), Arguments, With_NL, Locale,
         Catalog);
   end Print_Execute_Summary;

   -------------------------
   -- Print_Execute_Usage --
   -------------------------

   procedure Print_Execute_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (45), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Execute_Usage;

   --------------------------
   -- Print_Exit_Docstring --
   --------------------------

   procedure Print_Exit_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (26), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Exit_Docstring;

   ------------------------
   -- Print_Exit_Summary --
   ------------------------

   procedure Print_Exit_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (111), Arguments, With_NL, Locale,
         Catalog);
   end Print_Exit_Summary;

   ----------------------
   -- Print_Exit_Usage --
   ----------------------

   procedure Print_Exit_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (174), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Exit_Usage;

   ------------------------------
   -- Print_Filestat_Docstring --
   ------------------------------

   procedure Print_Filestat_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (5), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Filestat_Docstring;

   ----------------------------
   -- Print_Filestat_Summary --
   ----------------------------

   procedure Print_Filestat_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (44), Arguments, With_NL, Locale,
         Catalog);
   end Print_Filestat_Summary;

   --------------------------
   -- Print_Filestat_Usage --
   --------------------------

   procedure Print_Filestat_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (139), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Filestat_Usage;

   ----------------------------
   -- Print_Getenv_Docstring --
   ----------------------------

   procedure Print_Getenv_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (15), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Getenv_Docstring;

   --------------------------
   -- Print_Getenv_Summary --
   --------------------------

   procedure Print_Getenv_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (38), Arguments, With_NL, Locale,
         Catalog);
   end Print_Getenv_Summary;

   ------------------------
   -- Print_Getenv_Usage --
   ------------------------

   procedure Print_Getenv_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (68), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Getenv_Usage;

   --------------------------
   -- Print_Help_Docstring --
   --------------------------

   procedure Print_Help_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (10), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Help_Docstring;

   ------------------------
   -- Print_Help_Summary --
   ------------------------

   procedure Print_Help_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (49), Arguments, With_NL, Locale,
         Catalog);
   end Print_Help_Summary;

   ----------------------
   -- Print_Help_Usage --
   ----------------------

   procedure Print_Help_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (132), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Help_Usage;

   --------------------------
   -- Print_Incr_Docstring --
   --------------------------

   procedure Print_Incr_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (9), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Incr_Docstring;

   ------------------------
   -- Print_Incr_Summary --
   ------------------------

   procedure Print_Incr_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (99), Arguments, With_NL, Locale,
         Catalog);
   end Print_Incr_Summary;

   ----------------------
   -- Print_Incr_Usage --
   ----------------------

   procedure Print_Incr_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (151), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Incr_Usage;

   ---------------------------
   -- Print_Mkdir_Docstring --
   ---------------------------

   procedure Print_Mkdir_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (25), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Mkdir_Docstring;

   -------------------------
   -- Print_Mkdir_Summary --
   -------------------------

   procedure Print_Mkdir_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (124), Arguments, With_NL, Locale,
         Catalog);
   end Print_Mkdir_Summary;

   -----------------------
   -- Print_Mkdir_Usage --
   -----------------------

   procedure Print_Mkdir_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (164), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Mkdir_Usage;

   --------------------------
   -- Print_Noop_Docstring --
   --------------------------

   procedure Print_Noop_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (19), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Noop_Docstring;

   ------------------------
   -- Print_Noop_Summary --
   ------------------------

   procedure Print_Noop_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (105), Arguments, With_NL, Locale,
         Catalog);
   end Print_Noop_Summary;

   ----------------------
   -- Print_Noop_Usage --
   ----------------------

   procedure Print_Noop_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (175), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Noop_Usage;

   -----------------------------
   -- Print_Prepend_Docstring --
   -----------------------------

   procedure Print_Prepend_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (14), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Prepend_Docstring;

   ---------------------------
   -- Print_Prepend_Summary --
   ---------------------------

   procedure Print_Prepend_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (72), Arguments, With_NL, Locale,
         Catalog);
   end Print_Prepend_Summary;

   -------------------------
   -- Print_Prepend_Usage --
   -------------------------

   procedure Print_Prepend_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (136), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Prepend_Usage;

   ---------------------------
   -- Print_Print_Docstring --
   ---------------------------

   procedure Print_Print_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (7), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Print_Docstring;

   -------------------------
   -- Print_Print_Summary --
   -------------------------

   procedure Print_Print_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (90), Arguments, With_NL, Locale,
         Catalog);
   end Print_Print_Summary;

   -----------------------
   -- Print_Print_Usage --
   -----------------------

   procedure Print_Print_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (56), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Print_Usage;

   ----------------------------
   -- Print_Rename_Docstring --
   ----------------------------

   procedure Print_Rename_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (20), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Rename_Docstring;

   --------------------------
   -- Print_Rename_Summary --
   --------------------------

   procedure Print_Rename_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (80), Arguments, With_NL, Locale,
         Catalog);
   end Print_Rename_Summary;

   ------------------------
   -- Print_Rename_Usage --
   ------------------------

   procedure Print_Rename_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (134), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Rename_Usage;

   -------------------------
   -- Print_Run_Docstring --
   -------------------------

   procedure Print_Run_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (16), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Run_Docstring;

   -----------------------
   -- Print_Run_Summary --
   -----------------------

   procedure Print_Run_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (108), Arguments, With_NL, Locale,
         Catalog);
   end Print_Run_Summary;

   ---------------------
   -- Print_Run_Usage --
   ---------------------

   procedure Print_Run_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (163), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Run_Usage;

   -------------------------
   -- Print_Set_Docstring --
   -------------------------

   procedure Print_Set_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (4), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Set_Docstring;

   -----------------------
   -- Print_Set_Summary --
   -----------------------

   procedure Print_Set_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (101), Arguments, With_NL, Locale,
         Catalog);
   end Print_Set_Summary;

   ---------------------
   -- Print_Set_Usage --
   ---------------------

   procedure Print_Set_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (61), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Set_Usage;

   ----------------------------
   -- Print_Setenv_Docstring --
   ----------------------------

   procedure Print_Setenv_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (3), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Setenv_Docstring;

   --------------------------
   -- Print_Setenv_Summary --
   --------------------------

   procedure Print_Setenv_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (91), Arguments, With_NL, Locale,
         Catalog);
   end Print_Setenv_Summary;

   ------------------------
   -- Print_Setenv_Usage --
   ------------------------

   procedure Print_Setenv_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (104), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Setenv_Usage;

   ---------------------------
   -- Print_Which_Docstring --
   ---------------------------

   procedure Print_Which_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (13), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Which_Docstring;

   -------------------------
   -- Print_Which_Summary --
   -------------------------

   procedure Print_Which_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (63), Arguments, With_NL, Locale,
         Catalog);
   end Print_Which_Summary;

   -----------------------
   -- Print_Which_Usage --
   -----------------------

   procedure Print_Which_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (129), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Which_Usage;

end ZBTest_Messages.Commands_Prints;
