--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Functions_Exceptions is

   use ZanyBlue.Text.Formatting;

   -----------------------------
   -- Raise_Dirname_Docstring --
   -----------------------------

   procedure Raise_Dirname_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (21),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Dirname_Docstring;

   ---------------------------
   -- Raise_Dirname_Summary --
   ---------------------------

   procedure Raise_Dirname_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (2), Key (64),
                       Arguments, Locale, Catalog);
   end Raise_Dirname_Summary;

   -------------------------
   -- Raise_Dirname_Usage --
   -------------------------

   procedure Raise_Dirname_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (159),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Dirname_Usage;

   -------------------------------
   -- Raise_Joinpaths_Docstring --
   -------------------------------

   procedure Raise_Joinpaths_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (23),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Joinpaths_Docstring;

   -----------------------------
   -- Raise_Joinpaths_Summary --
   -----------------------------

   procedure Raise_Joinpaths_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (2), Key (33),
                       Arguments, Locale, Catalog);
   end Raise_Joinpaths_Summary;

   ---------------------------
   -- Raise_Joinpaths_Usage --
   ---------------------------

   procedure Raise_Joinpaths_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (149),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Joinpaths_Usage;

   -----------------------------
   -- Raise_Nextlog_Docstring --
   -----------------------------

   procedure Raise_Nextlog_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (2),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Nextlog_Docstring;

   ---------------------------
   -- Raise_Nextlog_Summary --
   ---------------------------

   procedure Raise_Nextlog_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (2), Key (62),
                       Arguments, Locale, Catalog);
   end Raise_Nextlog_Summary;

   -------------------------
   -- Raise_Nextlog_Usage --
   -------------------------

   procedure Raise_Nextlog_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (122),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Nextlog_Usage;

   ---------------------------
   -- Raise_Which_Docstring --
   ---------------------------

   procedure Raise_Which_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (13),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Which_Docstring;

   -------------------------
   -- Raise_Which_Summary --
   -------------------------

   procedure Raise_Which_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (2), Key (63),
                       Arguments, Locale, Catalog);
   end Raise_Which_Summary;

   -----------------------
   -- Raise_Which_Usage --
   -----------------------

   procedure Raise_Which_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (2), Key (129),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Which_Usage;

end ZBTest_Messages.Functions_Exceptions;
