--  -*- coding: utf-8 -*-
--
--  Ada specification generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Locales;
with ZanyBlue.Text.Arguments;

package ZBTest_Messages.Commands_Strings is

   use ZanyBlue.Text.Catalogs;
   use ZanyBlue.Text.Locales;
   use ZanyBlue.Text.Arguments;

   function Format_Append_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Append_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Append_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Begin_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Begin_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Begin_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Compare_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Compare_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Compare_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Copy_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Copy_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Copy_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delenv_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delenv_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delenv_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delete_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delete_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Delete_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Desc_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Desc_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Desc_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Dump_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Dump_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Dump_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Echo_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Echo_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Echo_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_End_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_End_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_End_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Execute_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Execute_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Execute_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Exit_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Exit_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Exit_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Filestat_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Filestat_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Filestat_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Getenv_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Getenv_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Getenv_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Help_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Help_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Help_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Incr_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Incr_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Incr_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Mkdir_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Mkdir_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Mkdir_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Noop_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Noop_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Noop_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Prepend_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Prepend_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Prepend_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Print_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Print_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Print_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Rename_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Rename_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Rename_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Run_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Run_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Run_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Set_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Set_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Set_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Setenv_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Setenv_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Setenv_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Which_Docstring
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Which_Summary
     (Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog)
      return String;

   function Format_Which_Usage
     (Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog)
      return String;

end ZBTest_Messages.Commands_Strings;
