--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada specification generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with UXStrings.Text_IO;
with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Locales;
with ZanyBlue.Text.Arguments;

package ZBTest_Messages.Functions_Prints is

   use UXStrings.Text_IO;
   use ZanyBlue.Text.Catalogs;
   use ZanyBlue.Text.Locales;
   use ZanyBlue.Text.Arguments;

   procedure Print_Dirname_Docstring (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Dirname_Summary (
      Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Dirname_Usage (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Joinpaths_Docstring (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Joinpaths_Summary (
      Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Joinpaths_Usage (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Nextlog_Docstring (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Nextlog_Summary (
      Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Nextlog_Usage (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Which_Docstring (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Which_Summary (
      Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

   procedure Print_Which_Usage (
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog);

end ZBTest_Messages.Functions_Prints;
