--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Commands_Strings is

   use ZanyBlue.Text.Formatting;

   -----------------------------
   -- Format_Append_Docstring --
   -----------------------------

   function Format_Append_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (12),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Append_Docstring;

   ---------------------------
   -- Format_Append_Summary --
   ---------------------------

   function Format_Append_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (74),
                     Arguments, Locale, Catalog);
   end Format_Append_Summary;

   -------------------------
   -- Format_Append_Usage --
   -------------------------

   function Format_Append_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (138),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Append_Usage;

   ----------------------------
   -- Format_Begin_Docstring --
   ----------------------------

   function Format_Begin_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (8),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Begin_Docstring;

   --------------------------
   -- Format_Begin_Summary --
   --------------------------

   function Format_Begin_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (96),
                     Arguments, Locale, Catalog);
   end Format_Begin_Summary;

   ------------------------
   -- Format_Begin_Usage --
   ------------------------

   function Format_Begin_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (173),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Begin_Usage;

   ------------------------------
   -- Format_Compare_Docstring --
   ------------------------------

   function Format_Compare_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (18),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Compare_Docstring;

   ----------------------------
   -- Format_Compare_Summary --
   ----------------------------

   function Format_Compare_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (60),
                     Arguments, Locale, Catalog);
   end Format_Compare_Summary;

   --------------------------
   -- Format_Compare_Usage --
   --------------------------

   function Format_Compare_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (109),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Compare_Usage;

   ---------------------------
   -- Format_Copy_Docstring --
   ---------------------------

   function Format_Copy_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (6),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Copy_Docstring;

   -------------------------
   -- Format_Copy_Summary --
   -------------------------

   function Format_Copy_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (97),
                     Arguments, Locale, Catalog);
   end Format_Copy_Summary;

   -----------------------
   -- Format_Copy_Usage --
   -----------------------

   function Format_Copy_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (143),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Copy_Usage;

   -----------------------------
   -- Format_Delenv_Docstring --
   -----------------------------

   function Format_Delenv_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (17),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Delenv_Docstring;

   ---------------------------
   -- Format_Delenv_Summary --
   ---------------------------

   function Format_Delenv_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (82),
                     Arguments, Locale, Catalog);
   end Format_Delenv_Summary;

   -------------------------
   -- Format_Delenv_Usage --
   -------------------------

   function Format_Delenv_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (160),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Delenv_Usage;

   -----------------------------
   -- Format_Delete_Docstring --
   -----------------------------

   function Format_Delete_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (27),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Delete_Docstring;

   ---------------------------
   -- Format_Delete_Summary --
   ---------------------------

   function Format_Delete_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (79),
                     Arguments, Locale, Catalog);
   end Format_Delete_Summary;

   -------------------------
   -- Format_Delete_Usage --
   -------------------------

   function Format_Delete_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (150),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Delete_Usage;

   ---------------------------
   -- Format_Desc_Docstring --
   ---------------------------

   function Format_Desc_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (30),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Desc_Docstring;

   -------------------------
   -- Format_Desc_Summary --
   -------------------------

   function Format_Desc_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (87),
                     Arguments, Locale, Catalog);
   end Format_Desc_Summary;

   -----------------------
   -- Format_Desc_Usage --
   -----------------------

   function Format_Desc_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (158),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Desc_Usage;

   ---------------------------
   -- Format_Dump_Docstring --
   ---------------------------

   function Format_Dump_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (22),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Dump_Docstring;

   -------------------------
   -- Format_Dump_Summary --
   -------------------------

   function Format_Dump_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (58),
                     Arguments, Locale, Catalog);
   end Format_Dump_Summary;

   -----------------------
   -- Format_Dump_Usage --
   -----------------------

   function Format_Dump_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (117),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Dump_Usage;

   ---------------------------
   -- Format_Echo_Docstring --
   ---------------------------

   function Format_Echo_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (24),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Echo_Docstring;

   -------------------------
   -- Format_Echo_Summary --
   -------------------------

   function Format_Echo_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (107),
                     Arguments, Locale, Catalog);
   end Format_Echo_Summary;

   -----------------------
   -- Format_Echo_Usage --
   -----------------------

   function Format_Echo_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (157),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Echo_Usage;

   --------------------------
   -- Format_End_Docstring --
   --------------------------

   function Format_End_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (11),
                     Empty_Argument_List, Locale, Catalog);
   end Format_End_Docstring;

   ------------------------
   -- Format_End_Summary --
   ------------------------

   function Format_End_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (50),
                     Arguments, Locale, Catalog);
   end Format_End_Summary;

   ----------------------
   -- Format_End_Usage --
   ----------------------

   function Format_End_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (177),
                     Empty_Argument_List, Locale, Catalog);
   end Format_End_Usage;

   ------------------------------
   -- Format_Execute_Docstring --
   ------------------------------

   function Format_Execute_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (1),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Execute_Docstring;

   ----------------------------
   -- Format_Execute_Summary --
   ----------------------------

   function Format_Execute_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (98),
                     Arguments, Locale, Catalog);
   end Format_Execute_Summary;

   --------------------------
   -- Format_Execute_Usage --
   --------------------------

   function Format_Execute_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (45),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Execute_Usage;

   ---------------------------
   -- Format_Exit_Docstring --
   ---------------------------

   function Format_Exit_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (26),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Exit_Docstring;

   -------------------------
   -- Format_Exit_Summary --
   -------------------------

   function Format_Exit_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (111),
                     Arguments, Locale, Catalog);
   end Format_Exit_Summary;

   -----------------------
   -- Format_Exit_Usage --
   -----------------------

   function Format_Exit_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (174),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Exit_Usage;

   -------------------------------
   -- Format_Filestat_Docstring --
   -------------------------------

   function Format_Filestat_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (5),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Filestat_Docstring;

   -----------------------------
   -- Format_Filestat_Summary --
   -----------------------------

   function Format_Filestat_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (44),
                     Arguments, Locale, Catalog);
   end Format_Filestat_Summary;

   ---------------------------
   -- Format_Filestat_Usage --
   ---------------------------

   function Format_Filestat_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (139),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Filestat_Usage;

   -----------------------------
   -- Format_Getenv_Docstring --
   -----------------------------

   function Format_Getenv_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (15),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Getenv_Docstring;

   ---------------------------
   -- Format_Getenv_Summary --
   ---------------------------

   function Format_Getenv_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (38),
                     Arguments, Locale, Catalog);
   end Format_Getenv_Summary;

   -------------------------
   -- Format_Getenv_Usage --
   -------------------------

   function Format_Getenv_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (68),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Getenv_Usage;

   ---------------------------
   -- Format_Help_Docstring --
   ---------------------------

   function Format_Help_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (10),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Help_Docstring;

   -------------------------
   -- Format_Help_Summary --
   -------------------------

   function Format_Help_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (49),
                     Arguments, Locale, Catalog);
   end Format_Help_Summary;

   -----------------------
   -- Format_Help_Usage --
   -----------------------

   function Format_Help_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (132),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Help_Usage;

   ---------------------------
   -- Format_Incr_Docstring --
   ---------------------------

   function Format_Incr_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (9),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Incr_Docstring;

   -------------------------
   -- Format_Incr_Summary --
   -------------------------

   function Format_Incr_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (99),
                     Arguments, Locale, Catalog);
   end Format_Incr_Summary;

   -----------------------
   -- Format_Incr_Usage --
   -----------------------

   function Format_Incr_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (151),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Incr_Usage;

   ----------------------------
   -- Format_Mkdir_Docstring --
   ----------------------------

   function Format_Mkdir_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (25),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Mkdir_Docstring;

   --------------------------
   -- Format_Mkdir_Summary --
   --------------------------

   function Format_Mkdir_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (124),
                     Arguments, Locale, Catalog);
   end Format_Mkdir_Summary;

   ------------------------
   -- Format_Mkdir_Usage --
   ------------------------

   function Format_Mkdir_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (164),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Mkdir_Usage;

   ---------------------------
   -- Format_Noop_Docstring --
   ---------------------------

   function Format_Noop_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (19),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Noop_Docstring;

   -------------------------
   -- Format_Noop_Summary --
   -------------------------

   function Format_Noop_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (105),
                     Arguments, Locale, Catalog);
   end Format_Noop_Summary;

   -----------------------
   -- Format_Noop_Usage --
   -----------------------

   function Format_Noop_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (175),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Noop_Usage;

   ------------------------------
   -- Format_Prepend_Docstring --
   ------------------------------

   function Format_Prepend_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (14),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Prepend_Docstring;

   ----------------------------
   -- Format_Prepend_Summary --
   ----------------------------

   function Format_Prepend_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (72),
                     Arguments, Locale, Catalog);
   end Format_Prepend_Summary;

   --------------------------
   -- Format_Prepend_Usage --
   --------------------------

   function Format_Prepend_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (136),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Prepend_Usage;

   ----------------------------
   -- Format_Print_Docstring --
   ----------------------------

   function Format_Print_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (7),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Print_Docstring;

   --------------------------
   -- Format_Print_Summary --
   --------------------------

   function Format_Print_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (90),
                     Arguments, Locale, Catalog);
   end Format_Print_Summary;

   ------------------------
   -- Format_Print_Usage --
   ------------------------

   function Format_Print_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (56),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Print_Usage;

   -----------------------------
   -- Format_Rename_Docstring --
   -----------------------------

   function Format_Rename_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (20),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Rename_Docstring;

   ---------------------------
   -- Format_Rename_Summary --
   ---------------------------

   function Format_Rename_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (80),
                     Arguments, Locale, Catalog);
   end Format_Rename_Summary;

   -------------------------
   -- Format_Rename_Usage --
   -------------------------

   function Format_Rename_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (134),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Rename_Usage;

   --------------------------
   -- Format_Run_Docstring --
   --------------------------

   function Format_Run_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (16),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Run_Docstring;

   ------------------------
   -- Format_Run_Summary --
   ------------------------

   function Format_Run_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (108),
                     Arguments, Locale, Catalog);
   end Format_Run_Summary;

   ----------------------
   -- Format_Run_Usage --
   ----------------------

   function Format_Run_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (163),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Run_Usage;

   --------------------------
   -- Format_Set_Docstring --
   --------------------------

   function Format_Set_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (4),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Set_Docstring;

   ------------------------
   -- Format_Set_Summary --
   ------------------------

   function Format_Set_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (101),
                     Arguments, Locale, Catalog);
   end Format_Set_Summary;

   ----------------------
   -- Format_Set_Usage --
   ----------------------

   function Format_Set_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (61),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Set_Usage;

   -----------------------------
   -- Format_Setenv_Docstring --
   -----------------------------

   function Format_Setenv_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (3),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Setenv_Docstring;

   ---------------------------
   -- Format_Setenv_Summary --
   ---------------------------

   function Format_Setenv_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (91),
                     Arguments, Locale, Catalog);
   end Format_Setenv_Summary;

   -------------------------
   -- Format_Setenv_Usage --
   -------------------------

   function Format_Setenv_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (104),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Setenv_Usage;

   ----------------------------
   -- Format_Which_Docstring --
   ----------------------------

   function Format_Which_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (13),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Which_Docstring;

   --------------------------
   -- Format_Which_Summary --
   --------------------------

   function Format_Which_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      return Format (Facility (1), Key (63),
                     Arguments, Locale, Catalog);
   end Format_Which_Summary;

   ------------------------
   -- Format_Which_Usage --
   ------------------------

   function Format_Which_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String
   is
   begin
      return Format (Facility (1), Key (129),
                     Empty_Argument_List, Locale, Catalog);
   end Format_Which_Usage;

end ZBTest_Messages.Commands_Strings;
