--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.ZBTest_Wide_Prints is

   use ZanyBlue.Text.Formatting;

   -----------------
   -- Print_00001 --
   -----------------

   procedure Print_00001
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Argument3   : Any_Category_Type'Class;
      Argument4   : Calendar_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Append (Arguments, Argument3);
      Append (Arguments, Argument4);
      Write_Message
        (Destination, Facility (1), Key (6), Arguments, With_NL, Locale,
         Catalog);
   end Print_00001;

   -----------------
   -- Print_00002 --
   -----------------

   procedure Print_00002
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (18), Arguments, With_NL, Locale,
         Catalog);
   end Print_00002;

   -----------------
   -- Print_00003 --
   -----------------

   procedure Print_00003
     (Argument0   : Calendar_Category_Type'Class;
      Argument1   : Duration_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (10), Arguments, With_NL, Locale,
         Catalog);
   end Print_00003;

   -----------------
   -- Print_00004 --
   -----------------

   procedure Print_00004
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (97), Arguments, With_NL, Locale,
         Catalog);
   end Print_00004;

   -----------------
   -- Print_00005 --
   -----------------

   procedure Print_00005
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (93), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00005;

   -----------------
   -- Print_00006 --
   -----------------

   procedure Print_00006
     (Argument0   : Integer_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (83), Arguments, With_NL, Locale,
         Catalog);
   end Print_00006;

   -----------------
   -- Print_00007 --
   -----------------

   procedure Print_00007
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (75), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00007;

   -----------------
   -- Print_00008 --
   -----------------

   procedure Print_00008
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (21), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00008;

   -----------------
   -- Print_00009 --
   -----------------

   procedure Print_00009
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (62), Arguments, With_NL, Locale,
         Catalog);
   end Print_00009;

   -----------------
   -- Print_00010 --
   -----------------

   procedure Print_00010
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (2), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00010;

   -----------------
   -- Print_00011 --
   -----------------

   procedure Print_00011
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (33), Arguments, With_NL, Locale,
         Catalog);
   end Print_00011;

   -----------------
   -- Print_00012 --
   -----------------

   procedure Print_00012
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (67), Arguments, With_NL, Locale,
         Catalog);
   end Print_00012;

   -----------------
   -- Print_00013 --
   -----------------

   procedure Print_00013
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (66), Arguments, With_NL, Locale,
         Catalog);
   end Print_00013;

   -----------------
   -- Print_00014 --
   -----------------

   procedure Print_00014
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (81), Arguments, With_NL, Locale,
         Catalog);
   end Print_00014;

   -----------------
   -- Print_00015 --
   -----------------

   procedure Print_00015
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (65), Arguments, With_NL, Locale,
         Catalog);
   end Print_00015;

   -----------------
   -- Print_00016 --
   -----------------

   procedure Print_00016
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (42), Arguments, With_NL, Locale,
         Catalog);
   end Print_00016;

   -----------------
   -- Print_00017 --
   -----------------

   procedure Print_00017
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (78), Arguments, With_NL, Locale,
         Catalog);
   end Print_00017;

   -----------------
   -- Print_00018 --
   -----------------

   procedure Print_00018
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Integer_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (25), Arguments, With_NL, Locale,
         Catalog);
   end Print_00018;

   -----------------
   -- Print_00019 --
   -----------------

   procedure Print_00019
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (23), Arguments, With_NL, Locale,
         Catalog);
   end Print_00019;

   -----------------
   -- Print_00020 --
   -----------------

   procedure Print_00020
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (73), Arguments, With_NL, Locale,
         Catalog);
   end Print_00020;

   -----------------
   -- Print_00021 --
   -----------------

   procedure Print_00021
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (74), Arguments, With_NL, Locale,
         Catalog);
   end Print_00021;

   -----------------
   -- Print_00022 --
   -----------------

   procedure Print_00022
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (31), Arguments, With_NL, Locale,
         Catalog);
   end Print_00022;

   -----------------
   -- Print_00023 --
   -----------------

   procedure Print_00023
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (15), Arguments, With_NL, Locale,
         Catalog);
   end Print_00023;

   -----------------
   -- Print_00024 --
   -----------------

   procedure Print_00024
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (70), Arguments, With_NL, Locale,
         Catalog);
   end Print_00024;

   -----------------
   -- Print_00025 --
   -----------------

   procedure Print_00025
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (86), Arguments, With_NL, Locale,
         Catalog);
   end Print_00025;

   -----------------
   -- Print_00026 --
   -----------------

   procedure Print_00026
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (89), Arguments, With_NL, Locale,
         Catalog);
   end Print_00026;

   -----------------
   -- Print_00027 --
   -----------------

   procedure Print_00027
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (90), Arguments, With_NL, Locale,
         Catalog);
   end Print_00027;

   -----------------
   -- Print_00028 --
   -----------------

   procedure Print_00028
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (91), Arguments, With_NL, Locale,
         Catalog);
   end Print_00028;

   -----------------
   -- Print_00029 --
   -----------------

   procedure Print_00029
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (72), Arguments, With_NL, Locale,
         Catalog);
   end Print_00029;

   -----------------
   -- Print_00030 --
   -----------------

   procedure Print_00030
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (7), Arguments, With_NL, Locale,
         Catalog);
   end Print_00030;

   -----------------
   -- Print_00031 --
   -----------------

   procedure Print_00031
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (41), Arguments, With_NL, Locale,
         Catalog);
   end Print_00031;

   -----------------
   -- Print_00032 --
   -----------------

   procedure Print_00032
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (55), Arguments, With_NL, Locale,
         Catalog);
   end Print_00032;

   -----------------
   -- Print_00033 --
   -----------------

   procedure Print_00033
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (95), Arguments, With_NL, Locale,
         Catalog);
   end Print_00033;

   -----------------
   -- Print_00034 --
   -----------------

   procedure Print_00034
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (87), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00034;

   -----------------
   -- Print_00035 --
   -----------------

   procedure Print_00035
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (85), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00035;

   -----------------
   -- Print_00036 --
   -----------------

   procedure Print_00036
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (69), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00036;

   -----------------
   -- Print_00037 --
   -----------------

   procedure Print_00037
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (88), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00037;

   -----------------
   -- Print_00038 --
   -----------------

   procedure Print_00038
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (39), Arguments, With_NL, Locale,
         Catalog);
   end Print_00038;

   -----------------
   -- Print_00039 --
   -----------------

   procedure Print_00039
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (16), Arguments, With_NL, Locale,
         Catalog);
   end Print_00039;

   -----------------
   -- Print_00040 --
   -----------------

   procedure Print_00040
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (61), Arguments, With_NL, Locale,
         Catalog);
   end Print_00040;

   -----------------
   -- Print_00041 --
   -----------------

   procedure Print_00041
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (71), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00041;

   -----------------
   -- Print_00042 --
   -----------------

   procedure Print_00042
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (14), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00042;

   -----------------
   -- Print_00043 --
   -----------------

   procedure Print_00043
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (77), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00043;

   -----------------
   -- Print_00044 --
   -----------------

   procedure Print_00044
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (79), Arguments, With_NL, Locale,
         Catalog);
   end Print_00044;

   -----------------
   -- Print_00045 --
   -----------------

   procedure Print_00045
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (51), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_00045;

   -----------------
   -- Print_00046 --
   -----------------

   procedure Print_00046
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (98), Arguments, With_NL, Locale,
         Catalog);
   end Print_00046;

   -----------------
   -- Print_00047 --
   -----------------

   procedure Print_00047
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (50), Arguments, With_NL, Locale,
         Catalog);
   end Print_00047;

   -----------------
   -- Print_01001 --
   -----------------

   procedure Print_01001
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (54), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_01001;

   -----------------
   -- Print_01002 --
   -----------------

   procedure Print_01002
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Argument3   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Append (Arguments, Argument3);
      Write_Message
        (Destination, Facility (1), Key (3), Arguments, With_NL, Locale,
         Catalog);
   end Print_01002;

   -----------------
   -- Print_01003 --
   -----------------

   procedure Print_01003
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (19), Arguments, With_NL, Locale,
         Catalog);
   end Print_01003;

   -----------------
   -- Print_01004 --
   -----------------

   procedure Print_01004
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (1), Arguments, With_NL, Locale,
         Catalog);
   end Print_01004;

   -----------------
   -- Print_01005 --
   -----------------

   procedure Print_01005
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (92), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_01005;

   -----------------
   -- Print_10001 --
   -----------------

   procedure Print_10001
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (48), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_10001;

   -----------------
   -- Print_10002 --
   -----------------

   procedure Print_10002
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (40), Arguments, With_NL, Locale,
         Catalog);
   end Print_10002;

   -----------------
   -- Print_10003 --
   -----------------

   procedure Print_10003
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (38), Arguments, With_NL, Locale,
         Catalog);
   end Print_10003;

   -----------------
   -- Print_10004 --
   -----------------

   procedure Print_10004
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (76), Arguments, With_NL, Locale,
         Catalog);
   end Print_10004;

   -----------------
   -- Print_10005 --
   -----------------

   procedure Print_10005
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (63), Arguments, With_NL, Locale,
         Catalog);
   end Print_10005;

   -----------------
   -- Print_10006 --
   -----------------

   procedure Print_10006
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (8), Arguments, With_NL, Locale,
         Catalog);
   end Print_10006;

   -----------------
   -- Print_10007 --
   -----------------

   procedure Print_10007
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (26), Arguments, With_NL, Locale,
         Catalog);
   end Print_10007;

   -----------------
   -- Print_10008 --
   -----------------

   procedure Print_10008
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (94), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_10008;

   -----------------
   -- Print_10009 --
   -----------------

   procedure Print_10009
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (60), Arguments, With_NL, Locale,
         Catalog);
   end Print_10009;

   -----------------
   -- Print_10010 --
   -----------------

   procedure Print_10010
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (56), Arguments, With_NL, Locale,
         Catalog);
   end Print_10010;

   -----------------
   -- Print_10011 --
   -----------------

   procedure Print_10011
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (27), Arguments, With_NL, Locale,
         Catalog);
   end Print_10011;

   -----------------
   -- Print_10012 --
   -----------------

   procedure Print_10012
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (20), Arguments, With_NL, Locale,
         Catalog);
   end Print_10012;

   -----------------
   -- Print_10013 --
   -----------------

   procedure Print_10013
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (28), Arguments, With_NL, Locale,
         Catalog);
   end Print_10013;

   -----------------
   -- Print_10014 --
   -----------------

   procedure Print_10014
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (35), Arguments, With_NL, Locale,
         Catalog);
   end Print_10014;

   -----------------
   -- Print_10015 --
   -----------------

   procedure Print_10015
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (49), Arguments, With_NL, Locale,
         Catalog);
   end Print_10015;

   -----------------
   -- Print_10016 --
   -----------------

   procedure Print_10016
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (45), Arguments, With_NL, Locale,
         Catalog);
   end Print_10016;

   -----------------
   -- Print_10017 --
   -----------------

   procedure Print_10017
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (96), Arguments, With_NL, Locale,
         Catalog);
   end Print_10017;

   -----------------
   -- Print_10018 --
   -----------------

   procedure Print_10018
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (22), Arguments, With_NL, Locale,
         Catalog);
   end Print_10018;

   -----------------
   -- Print_10019 --
   -----------------

   procedure Print_10019
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (44), Arguments, With_NL, Locale,
         Catalog);
   end Print_10019;

   -----------------
   -- Print_10020 --
   -----------------

   procedure Print_10020
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (37), Arguments, With_NL, Locale,
         Catalog);
   end Print_10020;

   -----------------
   -- Print_10021 --
   -----------------

   procedure Print_10021
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (17), Arguments, With_NL, Locale,
         Catalog);
   end Print_10021;

   -----------------
   -- Print_10022 --
   -----------------

   procedure Print_10022
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (52), Arguments, With_NL, Locale,
         Catalog);
   end Print_10022;

   -----------------
   -- Print_10023 --
   -----------------

   procedure Print_10023
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (80), Arguments, With_NL, Locale,
         Catalog);
   end Print_10023;

   -----------------
   -- Print_10024 --
   -----------------

   procedure Print_10024
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (84), Arguments, With_NL, Locale,
         Catalog);
   end Print_10024;

   -----------------
   -- Print_10025 --
   -----------------

   procedure Print_10025
     (Argument0   : Exception_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (11), Arguments, With_NL, Locale,
         Catalog);
   end Print_10025;

   -----------------
   -- Print_10026 --
   -----------------

   procedure Print_10026
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (57), Arguments, With_NL, Locale,
         Catalog);
   end Print_10026;

   -----------------
   -- Print_10027 --
   -----------------

   procedure Print_10027
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Exception_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (5), Arguments, With_NL, Locale,
         Catalog);
   end Print_10027;

   -----------------
   -- Print_10028 --
   -----------------

   procedure Print_10028
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (32), Arguments, With_NL, Locale,
         Catalog);
   end Print_10028;

   -----------------
   -- Print_10029 --
   -----------------

   procedure Print_10029
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (36), Arguments, With_NL, Locale,
         Catalog);
   end Print_10029;

   -----------------
   -- Print_10030 --
   -----------------

   procedure Print_10030
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (34), Arguments, With_NL, Locale,
         Catalog);
   end Print_10030;

   -----------------
   -- Print_10031 --
   -----------------

   procedure Print_10031
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (68), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_10031;

   -----------------
   -- Print_10032 --
   -----------------

   procedure Print_10032
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (29), Arguments, With_NL, Locale,
         Catalog);
   end Print_10032;

   -----------------
   -- Print_10033 --
   -----------------

   procedure Print_10033
     (Argument0   : Exception_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (4), Arguments, With_NL, Locale,
         Catalog);
   end Print_10033;

   -----------------
   -- Print_10034 --
   -----------------

   procedure Print_10034
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Write_Message
        (Destination, Facility (1), Key (46), Arguments, With_NL, Locale,
         Catalog);
   end Print_10034;

   -----------------
   -- Print_10035 --
   -----------------

   procedure Print_10035
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (47), Arguments, With_NL, Locale,
         Catalog);
   end Print_10035;

   -----------------
   -- Print_10036 --
   -----------------

   procedure Print_10036
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (43), Arguments, With_NL, Locale,
         Catalog);
   end Print_10036;

   -----------------
   -- Print_10037 --
   -----------------

   procedure Print_10037
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (59), Arguments, With_NL, Locale,
         Catalog);
   end Print_10037;

   -----------------
   -- Print_10038 --
   -----------------

   procedure Print_10038
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (64), Arguments, With_NL, Locale,
         Catalog);
   end Print_10038;

   -----------------
   -- Print_10039 --
   -----------------

   procedure Print_10039
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (9), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_10039;

   -----------------
   -- Print_10040 --
   -----------------

   procedure Print_10040
     (Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Write_Message
        (Destination, Facility (1), Key (30), Arguments, With_NL, Locale,
         Catalog);
   end Print_10040;

   -----------------
   -- Print_10041 --
   -----------------

   procedure Print_10041
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (13), Arguments, With_NL, Locale,
         Catalog);
   end Print_10041;

   -----------------
   -- Print_10042 --
   -----------------

   procedure Print_10042
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (53), Arguments, With_NL, Locale,
         Catalog);
   end Print_10042;

   -----------------
   -- Print_10043 --
   -----------------

   procedure Print_10043
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (12), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_10043;

   -----------------
   -- Print_20000 --
   -----------------

   procedure Print_20000
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (58), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_20000;

   -----------------
   -- Print_30000 --
   -----------------

   procedure Print_30000
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (1), Key (24), Arguments, With_NL, Locale,
         Catalog);
   end Print_30000;

   -----------------
   -- Print_40000 --
   -----------------

   procedure Print_40000
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (1), Key (82), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_40000;

end ZBTest_Messages.ZBTest_Wide_Prints;
