--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Commands_Exceptions is

   use ZanyBlue.Text.Formatting;

   ----------------------------
   -- Raise_Append_Docstring --
   ----------------------------

   procedure Raise_Append_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (12),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Append_Docstring;

   --------------------------
   -- Raise_Append_Summary --
   --------------------------

   procedure Raise_Append_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (74),
                       Arguments, Locale, Catalog);
   end Raise_Append_Summary;

   ------------------------
   -- Raise_Append_Usage --
   ------------------------

   procedure Raise_Append_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (138),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Append_Usage;

   ---------------------------
   -- Raise_Begin_Docstring --
   ---------------------------

   procedure Raise_Begin_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (8),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Begin_Docstring;

   -------------------------
   -- Raise_Begin_Summary --
   -------------------------

   procedure Raise_Begin_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (96),
                       Arguments, Locale, Catalog);
   end Raise_Begin_Summary;

   -----------------------
   -- Raise_Begin_Usage --
   -----------------------

   procedure Raise_Begin_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (173),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Begin_Usage;

   -----------------------------
   -- Raise_Compare_Docstring --
   -----------------------------

   procedure Raise_Compare_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (18),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Compare_Docstring;

   ---------------------------
   -- Raise_Compare_Summary --
   ---------------------------

   procedure Raise_Compare_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (60),
                       Arguments, Locale, Catalog);
   end Raise_Compare_Summary;

   -------------------------
   -- Raise_Compare_Usage --
   -------------------------

   procedure Raise_Compare_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (109),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Compare_Usage;

   --------------------------
   -- Raise_Copy_Docstring --
   --------------------------

   procedure Raise_Copy_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (6),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Copy_Docstring;

   ------------------------
   -- Raise_Copy_Summary --
   ------------------------

   procedure Raise_Copy_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (97),
                       Arguments, Locale, Catalog);
   end Raise_Copy_Summary;

   ----------------------
   -- Raise_Copy_Usage --
   ----------------------

   procedure Raise_Copy_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (143),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Copy_Usage;

   ----------------------------
   -- Raise_Delenv_Docstring --
   ----------------------------

   procedure Raise_Delenv_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (17),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Delenv_Docstring;

   --------------------------
   -- Raise_Delenv_Summary --
   --------------------------

   procedure Raise_Delenv_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (82),
                       Arguments, Locale, Catalog);
   end Raise_Delenv_Summary;

   ------------------------
   -- Raise_Delenv_Usage --
   ------------------------

   procedure Raise_Delenv_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (160),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Delenv_Usage;

   ----------------------------
   -- Raise_Delete_Docstring --
   ----------------------------

   procedure Raise_Delete_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (27),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Delete_Docstring;

   --------------------------
   -- Raise_Delete_Summary --
   --------------------------

   procedure Raise_Delete_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (79),
                       Arguments, Locale, Catalog);
   end Raise_Delete_Summary;

   ------------------------
   -- Raise_Delete_Usage --
   ------------------------

   procedure Raise_Delete_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (150),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Delete_Usage;

   --------------------------
   -- Raise_Desc_Docstring --
   --------------------------

   procedure Raise_Desc_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (30),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Desc_Docstring;

   ------------------------
   -- Raise_Desc_Summary --
   ------------------------

   procedure Raise_Desc_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (87),
                       Arguments, Locale, Catalog);
   end Raise_Desc_Summary;

   ----------------------
   -- Raise_Desc_Usage --
   ----------------------

   procedure Raise_Desc_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (158),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Desc_Usage;

   --------------------------
   -- Raise_Dump_Docstring --
   --------------------------

   procedure Raise_Dump_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (22),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Dump_Docstring;

   ------------------------
   -- Raise_Dump_Summary --
   ------------------------

   procedure Raise_Dump_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (58),
                       Arguments, Locale, Catalog);
   end Raise_Dump_Summary;

   ----------------------
   -- Raise_Dump_Usage --
   ----------------------

   procedure Raise_Dump_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (117),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Dump_Usage;

   --------------------------
   -- Raise_Echo_Docstring --
   --------------------------

   procedure Raise_Echo_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (24),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Echo_Docstring;

   ------------------------
   -- Raise_Echo_Summary --
   ------------------------

   procedure Raise_Echo_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (107),
                       Arguments, Locale, Catalog);
   end Raise_Echo_Summary;

   ----------------------
   -- Raise_Echo_Usage --
   ----------------------

   procedure Raise_Echo_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (157),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Echo_Usage;

   -------------------------
   -- Raise_End_Docstring --
   -------------------------

   procedure Raise_End_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (11),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_End_Docstring;

   -----------------------
   -- Raise_End_Summary --
   -----------------------

   procedure Raise_End_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (50),
                       Arguments, Locale, Catalog);
   end Raise_End_Summary;

   ---------------------
   -- Raise_End_Usage --
   ---------------------

   procedure Raise_End_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (177),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_End_Usage;

   -----------------------------
   -- Raise_Execute_Docstring --
   -----------------------------

   procedure Raise_Execute_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (1),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Execute_Docstring;

   ---------------------------
   -- Raise_Execute_Summary --
   ---------------------------

   procedure Raise_Execute_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (98),
                       Arguments, Locale, Catalog);
   end Raise_Execute_Summary;

   -------------------------
   -- Raise_Execute_Usage --
   -------------------------

   procedure Raise_Execute_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (45),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Execute_Usage;

   --------------------------
   -- Raise_Exit_Docstring --
   --------------------------

   procedure Raise_Exit_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (26),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Exit_Docstring;

   ------------------------
   -- Raise_Exit_Summary --
   ------------------------

   procedure Raise_Exit_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (111),
                       Arguments, Locale, Catalog);
   end Raise_Exit_Summary;

   ----------------------
   -- Raise_Exit_Usage --
   ----------------------

   procedure Raise_Exit_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (174),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Exit_Usage;

   ------------------------------
   -- Raise_Filestat_Docstring --
   ------------------------------

   procedure Raise_Filestat_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (5),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Filestat_Docstring;

   ----------------------------
   -- Raise_Filestat_Summary --
   ----------------------------

   procedure Raise_Filestat_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (44),
                       Arguments, Locale, Catalog);
   end Raise_Filestat_Summary;

   --------------------------
   -- Raise_Filestat_Usage --
   --------------------------

   procedure Raise_Filestat_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (139),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Filestat_Usage;

   ----------------------------
   -- Raise_Getenv_Docstring --
   ----------------------------

   procedure Raise_Getenv_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (15),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Getenv_Docstring;

   --------------------------
   -- Raise_Getenv_Summary --
   --------------------------

   procedure Raise_Getenv_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (38),
                       Arguments, Locale, Catalog);
   end Raise_Getenv_Summary;

   ------------------------
   -- Raise_Getenv_Usage --
   ------------------------

   procedure Raise_Getenv_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (68),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Getenv_Usage;

   --------------------------
   -- Raise_Help_Docstring --
   --------------------------

   procedure Raise_Help_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (10),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Help_Docstring;

   ------------------------
   -- Raise_Help_Summary --
   ------------------------

   procedure Raise_Help_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (49),
                       Arguments, Locale, Catalog);
   end Raise_Help_Summary;

   ----------------------
   -- Raise_Help_Usage --
   ----------------------

   procedure Raise_Help_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (132),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Help_Usage;

   --------------------------
   -- Raise_Incr_Docstring --
   --------------------------

   procedure Raise_Incr_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (9),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Incr_Docstring;

   ------------------------
   -- Raise_Incr_Summary --
   ------------------------

   procedure Raise_Incr_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (99),
                       Arguments, Locale, Catalog);
   end Raise_Incr_Summary;

   ----------------------
   -- Raise_Incr_Usage --
   ----------------------

   procedure Raise_Incr_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (151),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Incr_Usage;

   ---------------------------
   -- Raise_Mkdir_Docstring --
   ---------------------------

   procedure Raise_Mkdir_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (25),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Mkdir_Docstring;

   -------------------------
   -- Raise_Mkdir_Summary --
   -------------------------

   procedure Raise_Mkdir_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (124),
                       Arguments, Locale, Catalog);
   end Raise_Mkdir_Summary;

   -----------------------
   -- Raise_Mkdir_Usage --
   -----------------------

   procedure Raise_Mkdir_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (164),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Mkdir_Usage;

   --------------------------
   -- Raise_Noop_Docstring --
   --------------------------

   procedure Raise_Noop_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (19),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Noop_Docstring;

   ------------------------
   -- Raise_Noop_Summary --
   ------------------------

   procedure Raise_Noop_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (105),
                       Arguments, Locale, Catalog);
   end Raise_Noop_Summary;

   ----------------------
   -- Raise_Noop_Usage --
   ----------------------

   procedure Raise_Noop_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (175),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Noop_Usage;

   -----------------------------
   -- Raise_Prepend_Docstring --
   -----------------------------

   procedure Raise_Prepend_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (14),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Prepend_Docstring;

   ---------------------------
   -- Raise_Prepend_Summary --
   ---------------------------

   procedure Raise_Prepend_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (72),
                       Arguments, Locale, Catalog);
   end Raise_Prepend_Summary;

   -------------------------
   -- Raise_Prepend_Usage --
   -------------------------

   procedure Raise_Prepend_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (136),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Prepend_Usage;

   ---------------------------
   -- Raise_Print_Docstring --
   ---------------------------

   procedure Raise_Print_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (7),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Print_Docstring;

   -------------------------
   -- Raise_Print_Summary --
   -------------------------

   procedure Raise_Print_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (90),
                       Arguments, Locale, Catalog);
   end Raise_Print_Summary;

   -----------------------
   -- Raise_Print_Usage --
   -----------------------

   procedure Raise_Print_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (56),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Print_Usage;

   ----------------------------
   -- Raise_Rename_Docstring --
   ----------------------------

   procedure Raise_Rename_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (20),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Rename_Docstring;

   --------------------------
   -- Raise_Rename_Summary --
   --------------------------

   procedure Raise_Rename_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (80),
                       Arguments, Locale, Catalog);
   end Raise_Rename_Summary;

   ------------------------
   -- Raise_Rename_Usage --
   ------------------------

   procedure Raise_Rename_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (134),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Rename_Usage;

   -------------------------
   -- Raise_Run_Docstring --
   -------------------------

   procedure Raise_Run_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (16),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Run_Docstring;

   -----------------------
   -- Raise_Run_Summary --
   -----------------------

   procedure Raise_Run_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (108),
                       Arguments, Locale, Catalog);
   end Raise_Run_Summary;

   ---------------------
   -- Raise_Run_Usage --
   ---------------------

   procedure Raise_Run_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (163),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Run_Usage;

   -------------------------
   -- Raise_Set_Docstring --
   -------------------------

   procedure Raise_Set_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (4),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Set_Docstring;

   -----------------------
   -- Raise_Set_Summary --
   -----------------------

   procedure Raise_Set_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (101),
                       Arguments, Locale, Catalog);
   end Raise_Set_Summary;

   ---------------------
   -- Raise_Set_Usage --
   ---------------------

   procedure Raise_Set_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (61),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Set_Usage;

   ----------------------------
   -- Raise_Setenv_Docstring --
   ----------------------------

   procedure Raise_Setenv_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (3),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Setenv_Docstring;

   --------------------------
   -- Raise_Setenv_Summary --
   --------------------------

   procedure Raise_Setenv_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (91),
                       Arguments, Locale, Catalog);
   end Raise_Setenv_Summary;

   ------------------------
   -- Raise_Setenv_Usage --
   ------------------------

   procedure Raise_Setenv_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (104),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Setenv_Usage;

   ---------------------------
   -- Raise_Which_Docstring --
   ---------------------------

   procedure Raise_Which_Docstring (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (13),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Which_Docstring;

   -------------------------
   -- Raise_Which_Summary --
   -------------------------

   procedure Raise_Which_Summary (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (1), Key (63),
                       Arguments, Locale, Catalog);
   end Raise_Which_Summary;

   -----------------------
   -- Raise_Which_Usage --
   -----------------------

   procedure Raise_Which_Usage (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (1), Key (129),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_Which_Usage;

end ZBTest_Messages.Commands_Exceptions;
