--  -*- coding: utf-8 -*-
--
--  Ada specification generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with Ada.Exceptions;
with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Locales;
with ZanyBlue.Text.Arguments;

package ZBTest_Messages.ZBTest_Exceptions is

   use ZanyBlue.Text.Catalogs;
   use ZanyBlue.Text.Locales;
   use ZanyBlue.Text.Arguments;

   procedure Raise_00001
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Argument3 : Any_Category_Type'Class;
      Argument4 : Calendar_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00001);

   procedure Raise_00002
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00002);

   procedure Raise_00003
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Calendar_Category_Type'Class;
      Argument1 : Duration_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00003);

   procedure Raise_00004
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00004);

   procedure Raise_00005
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00005);

   procedure Raise_00006
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Integer_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00006);

   procedure Raise_00007
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00007);

   procedure Raise_00008
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00008);

   procedure Raise_00009
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00009);

   procedure Raise_00010
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00010);

   procedure Raise_00011
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00011);

   procedure Raise_00012
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00012);

   procedure Raise_00013
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00013);

   procedure Raise_00014
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Integer_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00014);

   procedure Raise_00015
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00015);

   procedure Raise_00016
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Integer_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00016);

   procedure Raise_00017
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00017);

   procedure Raise_00018
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Integer_Category_Type'Class;
      Argument2 : Integer_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00018);

   procedure Raise_00019
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00019);

   procedure Raise_00020
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00020);

   procedure Raise_00021
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00021);

   procedure Raise_00022
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00022);

   procedure Raise_00023
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00023);

   procedure Raise_00024
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00024);

   procedure Raise_00025
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00025);

   procedure Raise_00026
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00026);

   procedure Raise_00027
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00027);

   procedure Raise_00028
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00028);

   procedure Raise_00029
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00029);

   procedure Raise_00030
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00030);

   procedure Raise_00031
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00031);

   procedure Raise_00032
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00032);

   procedure Raise_00033
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00033);

   procedure Raise_00034
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00034);

   procedure Raise_00035
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00035);

   procedure Raise_00036
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00036);

   procedure Raise_00037
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00037);

   procedure Raise_00038
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00038);

   procedure Raise_00039
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00039);

   procedure Raise_00040
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00040);

   procedure Raise_00041
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00041);

   procedure Raise_00042
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00042);

   procedure Raise_00043
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00043);

   procedure Raise_00044
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Integer_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00044);

   procedure Raise_00045
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00045);

   procedure Raise_00046
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00046);

   procedure Raise_00047
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_00047);

   procedure Raise_01001
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_01001);

   procedure Raise_01002
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Argument3 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_01002);

   procedure Raise_01003
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_01003);

   procedure Raise_01004
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_01004);

   procedure Raise_01005
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_01005);

   procedure Raise_10001
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10001);

   procedure Raise_10002
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10002);

   procedure Raise_10003
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10003);

   procedure Raise_10004
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10004);

   procedure Raise_10005
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10005);

   procedure Raise_10006
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10006);

   procedure Raise_10007
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10007);

   procedure Raise_10008
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10008);

   procedure Raise_10009
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10009);

   procedure Raise_10010
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10010);

   procedure Raise_10011
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10011);

   procedure Raise_10012
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10012);

   procedure Raise_10013
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10013);

   procedure Raise_10014
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10014);

   procedure Raise_10015
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10015);

   procedure Raise_10016
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10016);

   procedure Raise_10017
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10017);

   procedure Raise_10018
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10018);

   procedure Raise_10019
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10019);

   procedure Raise_10020
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10020);

   procedure Raise_10021
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10021);

   procedure Raise_10022
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10022);

   procedure Raise_10023
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10023);

   procedure Raise_10024
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10024);

   procedure Raise_10025
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Exception_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10025);

   procedure Raise_10026
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10026);

   procedure Raise_10027
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Exception_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10027);

   procedure Raise_10028
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10028);

   procedure Raise_10029
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10029);

   procedure Raise_10030
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10030);

   procedure Raise_10031
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10031);

   procedure Raise_10032
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10032);

   procedure Raise_10033
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Exception_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10033);

   procedure Raise_10034
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Argument2 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10034);

   procedure Raise_10035
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10035);

   procedure Raise_10036
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10036);

   procedure Raise_10037
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10037);

   procedure Raise_10038
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10038);

   procedure Raise_10039
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10039);

   procedure Raise_10040
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Argument1 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10040);

   procedure Raise_10041
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10041);

   procedure Raise_10042
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10042);

   procedure Raise_10043
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_10043);

   procedure Raise_20000
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_20000);

   procedure Raise_30000
     (E         : Ada.Exceptions.Exception_Id;
      Argument0 : Any_Category_Type'Class;
      Locale    : Locale_Type  := Current_Locale;
      Catalog   : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_30000);

   procedure Raise_40000
     (E       : Ada.Exceptions.Exception_Id;
      Locale  : Locale_Type  := Current_Locale;
      Catalog : Catalog_Type := Standard_Catalog);
   pragma No_Return (Raise_40000);

end ZBTest_Messages.ZBTest_Exceptions;
