--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada specification generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Catalogs;
with ZanyBlue.Text.Locales;
with ZanyBlue.Text.Arguments;

package ZBTest_Messages.Functions_Strings is

   use ZanyBlue.Text.Catalogs;
   use ZanyBlue.Text.Locales;
   use ZanyBlue.Text.Arguments;

   function Format_Dirname_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Dirname_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Dirname_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Joinpaths_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Joinpaths_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Joinpaths_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Nextlog_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Nextlog_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Nextlog_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Which_Docstring (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Which_Summary (
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

   function Format_Which_Usage (
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog) return String;

end ZBTest_Messages.Functions_Strings;
