--!pp off
--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.ZBTest_Exceptions is

   use ZanyBlue.Text.Formatting;

   -----------------
   -- Raise_00001 --
   -----------------

   procedure Raise_00001 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Argument3   : Any_Category_Type'Class;
      Argument4   : Calendar_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Append (Arguments, Argument3);
      Append (Arguments, Argument4);
      Raise_Exception (E, Facility (3), Key (35),
                       Arguments, Locale, Catalog);
   end Raise_00001;

   -----------------
   -- Raise_00002 --
   -----------------

   procedure Raise_00002 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (53),
                       Arguments, Locale, Catalog);
   end Raise_00002;

   -----------------
   -- Raise_00003 --
   -----------------

   procedure Raise_00003 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Calendar_Category_Type'Class;
      Argument1   : Duration_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (40),
                       Arguments, Locale, Catalog);
   end Raise_00003;

   -----------------
   -- Raise_00004 --
   -----------------

   procedure Raise_00004 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (182),
                       Arguments, Locale, Catalog);
   end Raise_00004;

   -----------------
   -- Raise_00005 --
   -----------------

   procedure Raise_00005 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (176),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00005;

   -----------------
   -- Raise_00006 --
   -----------------

   procedure Raise_00006 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Integer_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (161),
                       Arguments, Locale, Catalog);
   end Raise_00006;

   -----------------
   -- Raise_00007 --
   -----------------

   procedure Raise_00007 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (145),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00007;

   -----------------
   -- Raise_00008 --
   -----------------

   procedure Raise_00008 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (55),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00008;

   -----------------
   -- Raise_00009 --
   -----------------

   procedure Raise_00009 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (127),
                       Arguments, Locale, Catalog);
   end Raise_00009;

   -----------------
   -- Raise_00010 --
   -----------------

   procedure Raise_00010 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (29),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00010;

   -----------------
   -- Raise_00011 --
   -----------------

   procedure Raise_00011 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (77),
                       Arguments, Locale, Catalog);
   end Raise_00011;

   -----------------
   -- Raise_00012 --
   -----------------

   procedure Raise_00012 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (133),
                       Arguments, Locale, Catalog);
   end Raise_00012;

   -----------------
   -- Raise_00013 --
   -----------------

   procedure Raise_00013 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (131),
                       Arguments, Locale, Catalog);
   end Raise_00013;

   -----------------
   -- Raise_00014 --
   -----------------

   procedure Raise_00014 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (153),
                       Arguments, Locale, Catalog);
   end Raise_00014;

   -----------------
   -- Raise_00015 --
   -----------------

   procedure Raise_00015 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (130),
                       Arguments, Locale, Catalog);
   end Raise_00015;

   -----------------
   -- Raise_00016 --
   -----------------

   procedure Raise_00016 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (92),
                       Arguments, Locale, Catalog);
   end Raise_00016;

   -----------------
   -- Raise_00017 --
   -----------------

   procedure Raise_00017 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (152),
                       Arguments, Locale, Catalog);
   end Raise_00017;

   -----------------
   -- Raise_00018 --
   -----------------

   procedure Raise_00018 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Integer_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (66),
                       Arguments, Locale, Catalog);
   end Raise_00018;

   -----------------
   -- Raise_00019 --
   -----------------

   procedure Raise_00019 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (59),
                       Arguments, Locale, Catalog);
   end Raise_00019;

   -----------------
   -- Raise_00020 --
   -----------------

   procedure Raise_00020 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (144),
                       Arguments, Locale, Catalog);
   end Raise_00020;

   -----------------
   -- Raise_00021 --
   -----------------

   procedure Raise_00021 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (146),
                       Arguments, Locale, Catalog);
   end Raise_00021;

   -----------------
   -- Raise_00022 --
   -----------------

   procedure Raise_00022 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (75),
                       Arguments, Locale, Catalog);
   end Raise_00022;

   -----------------
   -- Raise_00023 --
   -----------------

   procedure Raise_00023 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (48),
                       Arguments, Locale, Catalog);
   end Raise_00023;

   -----------------
   -- Raise_00024 --
   -----------------

   procedure Raise_00024 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (140),
                       Arguments, Locale, Catalog);
   end Raise_00024;

   -----------------
   -- Raise_00025 --
   -----------------

   procedure Raise_00025 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (166),
                       Arguments, Locale, Catalog);
   end Raise_00025;

   -----------------
   -- Raise_00026 --
   -----------------

   procedure Raise_00026 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (170),
                       Arguments, Locale, Catalog);
   end Raise_00026;

   -----------------
   -- Raise_00027 --
   -----------------

   procedure Raise_00027 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (171),
                       Arguments, Locale, Catalog);
   end Raise_00027;

   -----------------
   -- Raise_00028 --
   -----------------

   procedure Raise_00028 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (168),
                       Arguments, Locale, Catalog);
   end Raise_00028;

   -----------------
   -- Raise_00029 --
   -----------------

   procedure Raise_00029 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (142),
                       Arguments, Locale, Catalog);
   end Raise_00029;

   -----------------
   -- Raise_00030 --
   -----------------

   procedure Raise_00030 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (37),
                       Arguments, Locale, Catalog);
   end Raise_00030;

   -----------------
   -- Raise_00031 --
   -----------------

   procedure Raise_00031 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (88),
                       Arguments, Locale, Catalog);
   end Raise_00031;

   -----------------
   -- Raise_00032 --
   -----------------

   procedure Raise_00032 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (116),
                       Arguments, Locale, Catalog);
   end Raise_00032;

   -----------------
   -- Raise_00033 --
   -----------------

   procedure Raise_00033 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (179),
                       Arguments, Locale, Catalog);
   end Raise_00033;

   -----------------
   -- Raise_00034 --
   -----------------

   procedure Raise_00034 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (167),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00034;

   -----------------
   -- Raise_00035 --
   -----------------

   procedure Raise_00035 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (165),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00035;

   -----------------
   -- Raise_00036 --
   -----------------

   procedure Raise_00036 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (137),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00036;

   -----------------
   -- Raise_00037 --
   -----------------

   procedure Raise_00037 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (169),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00037;

   -----------------
   -- Raise_00038 --
   -----------------

   procedure Raise_00038 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (86),
                       Arguments, Locale, Catalog);
   end Raise_00038;

   -----------------
   -- Raise_00039 --
   -----------------

   procedure Raise_00039 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (47),
                       Arguments, Locale, Catalog);
   end Raise_00039;

   -----------------
   -- Raise_00040 --
   -----------------

   procedure Raise_00040 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (125),
                       Arguments, Locale, Catalog);
   end Raise_00040;

   -----------------
   -- Raise_00041 --
   -----------------

   procedure Raise_00041 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (141),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00041;

   -----------------
   -- Raise_00042 --
   -----------------

   procedure Raise_00042 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (42),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00042;

   -----------------
   -- Raise_00043 --
   -----------------

   procedure Raise_00043 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (148),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00043;

   -----------------
   -- Raise_00044 --
   -----------------

   procedure Raise_00044 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Integer_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (154),
                       Arguments, Locale, Catalog);
   end Raise_00044;

   -----------------
   -- Raise_00045 --
   -----------------

   procedure Raise_00045 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (113),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_00045;

   -----------------
   -- Raise_00046 --
   -----------------

   procedure Raise_00046 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (181),
                       Arguments, Locale, Catalog);
   end Raise_00046;

   -----------------
   -- Raise_00047 --
   -----------------

   procedure Raise_00047 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (112),
                       Arguments, Locale, Catalog);
   end Raise_00047;

   -----------------
   -- Raise_01001 --
   -----------------

   procedure Raise_01001 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (115),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_01001;

   -----------------
   -- Raise_01002 --
   -----------------

   procedure Raise_01002 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Argument3   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Append (Arguments, Argument3);
      Raise_Exception (E, Facility (3), Key (31),
                       Arguments, Locale, Catalog);
   end Raise_01002;

   -----------------
   -- Raise_01003 --
   -----------------

   procedure Raise_01003 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (52),
                       Arguments, Locale, Catalog);
   end Raise_01003;

   -----------------
   -- Raise_01004 --
   -----------------

   procedure Raise_01004 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (28),
                       Arguments, Locale, Catalog);
   end Raise_01004;

   -----------------
   -- Raise_01005 --
   -----------------

   procedure Raise_01005 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (172),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_01005;

   -----------------
   -- Raise_10001 --
   -----------------

   procedure Raise_10001 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (102),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_10001;

   -----------------
   -- Raise_10002 --
   -----------------

   procedure Raise_10002 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (89),
                       Arguments, Locale, Catalog);
   end Raise_10002;

   -----------------
   -- Raise_10003 --
   -----------------

   procedure Raise_10003 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (85),
                       Arguments, Locale, Catalog);
   end Raise_10003;

   -----------------
   -- Raise_10004 --
   -----------------

   procedure Raise_10004 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (147),
                       Arguments, Locale, Catalog);
   end Raise_10004;

   -----------------
   -- Raise_10005 --
   -----------------

   procedure Raise_10005 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (126),
                       Arguments, Locale, Catalog);
   end Raise_10005;

   -----------------
   -- Raise_10006 --
   -----------------

   procedure Raise_10006 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (36),
                       Arguments, Locale, Catalog);
   end Raise_10006;

   -----------------
   -- Raise_10007 --
   -----------------

   procedure Raise_10007 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (67),
                       Arguments, Locale, Catalog);
   end Raise_10007;

   -----------------
   -- Raise_10008 --
   -----------------

   procedure Raise_10008 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (178),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_10008;

   -----------------
   -- Raise_10009 --
   -----------------

   procedure Raise_10009 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (123),
                       Arguments, Locale, Catalog);
   end Raise_10009;

   -----------------
   -- Raise_10010 --
   -----------------

   procedure Raise_10010 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (118),
                       Arguments, Locale, Catalog);
   end Raise_10010;

   -----------------
   -- Raise_10011 --
   -----------------

   procedure Raise_10011 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (69),
                       Arguments, Locale, Catalog);
   end Raise_10011;

   -----------------
   -- Raise_10012 --
   -----------------

   procedure Raise_10012 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (54),
                       Arguments, Locale, Catalog);
   end Raise_10012;

   -----------------
   -- Raise_10013 --
   -----------------

   procedure Raise_10013 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (70),
                       Arguments, Locale, Catalog);
   end Raise_10013;

   -----------------
   -- Raise_10014 --
   -----------------

   procedure Raise_10014 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (81),
                       Arguments, Locale, Catalog);
   end Raise_10014;

   -----------------
   -- Raise_10015 --
   -----------------

   procedure Raise_10015 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (106),
                       Arguments, Locale, Catalog);
   end Raise_10015;

   -----------------
   -- Raise_10016 --
   -----------------

   procedure Raise_10016 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (95),
                       Arguments, Locale, Catalog);
   end Raise_10016;

   -----------------
   -- Raise_10017 --
   -----------------

   procedure Raise_10017 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (180),
                       Arguments, Locale, Catalog);
   end Raise_10017;

   -----------------
   -- Raise_10018 --
   -----------------

   procedure Raise_10018 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (57),
                       Arguments, Locale, Catalog);
   end Raise_10018;

   -----------------
   -- Raise_10019 --
   -----------------

   procedure Raise_10019 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (94),
                       Arguments, Locale, Catalog);
   end Raise_10019;

   -----------------
   -- Raise_10020 --
   -----------------

   procedure Raise_10020 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (84),
                       Arguments, Locale, Catalog);
   end Raise_10020;

   -----------------
   -- Raise_10021 --
   -----------------

   procedure Raise_10021 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (51),
                       Arguments, Locale, Catalog);
   end Raise_10021;

   -----------------
   -- Raise_10022 --
   -----------------

   procedure Raise_10022 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (110),
                       Arguments, Locale, Catalog);
   end Raise_10022;

   -----------------
   -- Raise_10023 --
   -----------------

   procedure Raise_10023 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (155),
                       Arguments, Locale, Catalog);
   end Raise_10023;

   -----------------
   -- Raise_10024 --
   -----------------

   procedure Raise_10024 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (162),
                       Arguments, Locale, Catalog);
   end Raise_10024;

   -----------------
   -- Raise_10025 --
   -----------------

   procedure Raise_10025 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Exception_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (41),
                       Arguments, Locale, Catalog);
   end Raise_10025;

   -----------------
   -- Raise_10026 --
   -----------------

   procedure Raise_10026 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (120),
                       Arguments, Locale, Catalog);
   end Raise_10026;

   -----------------
   -- Raise_10027 --
   -----------------

   procedure Raise_10027 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Exception_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (34),
                       Arguments, Locale, Catalog);
   end Raise_10027;

   -----------------
   -- Raise_10028 --
   -----------------

   procedure Raise_10028 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (76),
                       Arguments, Locale, Catalog);
   end Raise_10028;

   -----------------
   -- Raise_10029 --
   -----------------

   procedure Raise_10029 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (78),
                       Arguments, Locale, Catalog);
   end Raise_10029;

   -----------------
   -- Raise_10030 --
   -----------------

   procedure Raise_10030 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (83),
                       Arguments, Locale, Catalog);
   end Raise_10030;

   -----------------
   -- Raise_10031 --
   -----------------

   procedure Raise_10031 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (135),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_10031;

   -----------------
   -- Raise_10032 --
   -----------------

   procedure Raise_10032 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (73),
                       Arguments, Locale, Catalog);
   end Raise_10032;

   -----------------
   -- Raise_10033 --
   -----------------

   procedure Raise_10033 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Exception_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (32),
                       Arguments, Locale, Catalog);
   end Raise_10033;

   -----------------
   -- Raise_10034 --
   -----------------

   procedure Raise_10034 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Argument2   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Append (Arguments, Argument2);
      Raise_Exception (E, Facility (3), Key (100),
                       Arguments, Locale, Catalog);
   end Raise_10034;

   -----------------
   -- Raise_10035 --
   -----------------

   procedure Raise_10035 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (103),
                       Arguments, Locale, Catalog);
   end Raise_10035;

   -----------------
   -- Raise_10036 --
   -----------------

   procedure Raise_10036 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (93),
                       Arguments, Locale, Catalog);
   end Raise_10036;

   -----------------
   -- Raise_10037 --
   -----------------

   procedure Raise_10037 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (119),
                       Arguments, Locale, Catalog);
   end Raise_10037;

   -----------------
   -- Raise_10038 --
   -----------------

   procedure Raise_10038 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (128),
                       Arguments, Locale, Catalog);
   end Raise_10038;

   -----------------
   -- Raise_10039 --
   -----------------

   procedure Raise_10039 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (39),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_10039;

   -----------------
   -- Raise_10040 --
   -----------------

   procedure Raise_10040 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Argument1   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Append (Arguments, Argument1);
      Raise_Exception (E, Facility (3), Key (71),
                       Arguments, Locale, Catalog);
   end Raise_10040;

   -----------------
   -- Raise_10041 --
   -----------------

   procedure Raise_10041 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (46),
                       Arguments, Locale, Catalog);
   end Raise_10041;

   -----------------
   -- Raise_10042 --
   -----------------

   procedure Raise_10042 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (114),
                       Arguments, Locale, Catalog);
   end Raise_10042;

   -----------------
   -- Raise_10043 --
   -----------------

   procedure Raise_10043 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (43),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_10043;

   -----------------
   -- Raise_20000 --
   -----------------

   procedure Raise_20000 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (121),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_20000;

   -----------------
   -- Raise_30000 --
   -----------------

   procedure Raise_30000 (
      E           : Ada.Exceptions.Exception_Id;
      Argument0   : Any_Category_Type'Class;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Raise_Exception (E, Facility (3), Key (65),
                       Arguments, Locale, Catalog);
   end Raise_30000;

   -----------------
   -- Raise_40000 --
   -----------------

   procedure Raise_40000 (
      E           : Ada.Exceptions.Exception_Id;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Raise_Exception (E, Facility (3), Key (156),
                       Empty_Argument_List, Locale, Catalog);
   end Raise_40000;

end ZBTest_Messages.ZBTest_Exceptions;
