--  -*- coding: utf-8 -*-
--
--  Ada implementation generated by ZBMCompile, V2.0.0 (r3199).
--  This is a generated file and should not be edited.
--

with ZanyBlue.Text.Formatting;

package body ZBTest_Messages.Functions_Prints is

   use ZanyBlue.Text.Formatting;

   -----------------------------
   -- Print_Dirname_Docstring --
   -----------------------------

   procedure Print_Dirname_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (21), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Dirname_Docstring;

   ---------------------------
   -- Print_Dirname_Summary --
   ---------------------------

   procedure Print_Dirname_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (2), Key (64), Arguments, With_NL, Locale,
         Catalog);
   end Print_Dirname_Summary;

   -------------------------
   -- Print_Dirname_Usage --
   -------------------------

   procedure Print_Dirname_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (159), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Dirname_Usage;

   -------------------------------
   -- Print_Joinpaths_Docstring --
   -------------------------------

   procedure Print_Joinpaths_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (23), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Joinpaths_Docstring;

   -----------------------------
   -- Print_Joinpaths_Summary --
   -----------------------------

   procedure Print_Joinpaths_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (2), Key (33), Arguments, With_NL, Locale,
         Catalog);
   end Print_Joinpaths_Summary;

   ---------------------------
   -- Print_Joinpaths_Usage --
   ---------------------------

   procedure Print_Joinpaths_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (149), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Joinpaths_Usage;

   -----------------------------
   -- Print_Nextlog_Docstring --
   -----------------------------

   procedure Print_Nextlog_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (2), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Nextlog_Docstring;

   ---------------------------
   -- Print_Nextlog_Summary --
   ---------------------------

   procedure Print_Nextlog_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (2), Key (62), Arguments, With_NL, Locale,
         Catalog);
   end Print_Nextlog_Summary;

   -------------------------
   -- Print_Nextlog_Usage --
   -------------------------

   procedure Print_Nextlog_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (122), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Nextlog_Usage;

   ---------------------------
   -- Print_Which_Docstring --
   ---------------------------

   procedure Print_Which_Docstring
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (13), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Which_Docstring;

   -------------------------
   -- Print_Which_Summary --
   -------------------------

   procedure Print_Which_Summary
     (Argument0   : Any_Category_Type'Class;
      Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
      Arguments : Argument_List;
   begin
      Append (Arguments, Argument0);
      Write_Message
        (Destination, Facility (2), Key (63), Arguments, With_NL, Locale,
         Catalog);
   end Print_Which_Summary;

   -----------------------
   -- Print_Which_Usage --
   -----------------------

   procedure Print_Which_Usage
     (Destination : File_Type    := Current_Output;
      With_NL     : Boolean      := True;
      Locale      : Locale_Type  := Current_Locale;
      Catalog     : Catalog_Type := Standard_Catalog)
   is
   begin
      Write_Message
        (Destination, Facility (2), Key (129), Empty_Argument_List, With_NL,
         Locale, Catalog);
   end Print_Which_Usage;

end ZBTest_Messages.Functions_Prints;
